import{compileVectorField}from'../../src/lib/math/expression.js';
import{parseDesmosSlopeField,parseDesmosVectorField}from'./core/desmosLatex.js';
const CHANNEL='fieldplay-desmos',settings={arrows:true,particles:true,particleCount:1400,particleSpeed:1};
const arrowCanvas=makeCanvas('fieldplay-desmos-overlay'),particleCanvas=makeCanvas('fieldplay-desmos-particles'),arrowContext=arrowCanvas.getContext('2d',{alpha:true}),particleContext=particleCanvas.getContext('2d',{alpha:true}),status=document.createElement('button'),menu=document.createElement('div');
let state,field,frame=0,lastTime=performance.now(),particles=[];
status.id='fieldplay-desmos-status';status.type='button';status.title='FieldPlay controls';status.textContent='FieldPlay: waiting';
menu.id='fieldplay-desmos-menu';menu.hidden=true;menu.innerHTML=`<div class="fieldplay-title">FieldPlay overlay</div><label><input type="checkbox" data-setting="arrows" checked> Vector arrows</label><label><input type="checkbox" data-setting="particles" checked> Flow particles</label><label class="fieldplay-range">Particles <input type="range" data-setting="particleCount" min="200" max="5000" step="200" value="1400"><output>1400</output></label><label class="fieldplay-range">Speed <input type="range" data-setting="particleSpeed" min="0.2" max="2.5" step="0.1" value="1"><output>1.0×</output></label><div class="fieldplay-hint">Alt+V toggles everything</div>`;
document.documentElement.append(arrowCanvas,particleCanvas,status,menu);
chrome.storage?.local.get(settings,saved=>{Object.assign(settings,saved);syncControls();resetParticles();schedule();});
window.addEventListener('message',event=>{if(event.source!==window||event.data?.channel!==CHANNEL||event.data.type!=='state')return;state=event.data.payload;updateField();schedule();});
window.addEventListener('resize',schedule);document.addEventListener('keydown',event=>{if(event.altKey&&event.key.toLowerCase()==='v'){const enabled=settings.arrows||settings.particles;settings.arrows=!enabled;settings.particles=!enabled;saveSettings();syncControls();schedule();}});
status.addEventListener('click',()=>{menu.hidden=!menu.hidden;});document.addEventListener('pointerdown',event=>{if(!menu.hidden&&!menu.contains(event.target)&&event.target!==status)menu.hidden=true;});
menu.addEventListener('input',event=>{const key=event.target.dataset.setting;if(!key)return;settings[key]=event.target.type==='checkbox'?event.target.checked:Number(event.target.value);if(key==='particleCount')resetParticles();saveSettings();syncControls();schedule();});
function makeCanvas(id){const element=document.createElement('canvas');element.id=id;return element;}
function saveSettings(){chrome.storage?.local.set(settings);}
function syncControls(){for(const input of menu.querySelectorAll('[data-setting]')){const key=input.dataset.setting;if(input.type==='checkbox')input.checked=settings[key];else input.value=settings[key];const output=input.parentElement.querySelector('output');if(output)output.textContent=key==='particleSpeed'?`${Number(settings[key]).toFixed(1)}×`:String(settings[key]);}status.dataset.disabled=String(!settings.arrows&&!settings.particles);}
function updateField(){field=null;if(state?.mode==='2d')for(const expression of state.expressions){if(expression.hidden)continue;const parsed=parseDesmosVectorField(expression.latex)||parseDesmosSlopeField(expression.latex);if(!parsed)continue;try{field={...parsed,model:compileVectorField(parsed.x,parsed.y)};break;}catch(error){status.textContent=`FieldPlay: ${error.message}`;return;}}status.textContent=field?`FieldPlay: ${field.name}${field.kind==='slope-field'?'':'(x,y)'}`:'FieldPlay: vec F=<<P,Q>> or y\'=f(x,y)';}
function schedule(){if(!frame)frame=requestAnimationFrame(draw);}
function draw(now){frame=0;const dt=Math.min(.04,Math.max(0,(now-lastTime)/1000));lastTime=now;resize(arrowCanvas);resize(particleCanvas);clear(arrowContext,arrowCanvas);clear(particleContext,particleCanvas);if(field&&state?.bounds&&state?.viewport){if(settings.arrows)drawArrows();if(settings.particles)drawParticles(dt);}if(settings.particles)schedule();}
function clear(context,canvas){context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,canvas.width,canvas.height);}
function viewport(){const math=state.bounds.mathCoordinates,screen=state.viewport;return{math,screen,dpr:Math.min(devicePixelRatio||1,2),width:screen.width,height:screen.height};}
function drawArrows(){const{math,screen,dpr,width,height}=viewport(),rows=Math.max(12,Math.round(height/40)),cols=Math.max(10,Math.round(width/40)),cell=Math.min(width/cols,height/rows),maxLength=cell*.72,samples=[];for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=math.left+(i+.5)/cols*(math.right-math.left),y=math.top+(j+.5)/rows*(math.bottom-math.top),v=field.model.evaluate(x,y),m=Math.hypot(v[0],v[1]);if(Number.isFinite(m)&&m>1e-10)samples.push({i,j,v,m});}const magnitudes=samples.map(sample=>sample.m).sort((a,b)=>a-b),scale=magnitudes[Math.floor(magnitudes.length*.92)]||1;arrowContext.setTransform(dpr,0,0,dpr,0,0);clip(arrowContext,screen);arrowContext.lineCap='round';for(const sample of samples){const cx=screen.left+(sample.i+.5)/cols*width,cy=screen.top+(sample.j+.5)/rows*height,ux=sample.v[0]/sample.m,uy=-sample.v[1]/sample.m,length=maxLength*(.28+.72*Math.sqrt(Math.min(1,sample.m/scale))),x1=cx-ux*length/2,y1=cy-uy*length/2,x2=cx+ux*length/2,y2=cy+uy*length/2,angle=Math.atan2(y2-y1,x2-x1),head=Math.min(6,length*.3),t=Math.min(1,sample.m/scale);arrowContext.strokeStyle=`hsla(${195-155*t},92%,${68-15*t}%,.88)`;arrowContext.fillStyle=arrowContext.strokeStyle;arrowContext.lineWidth=1.4;arrowContext.beginPath();arrowContext.moveTo(x1,y1);arrowContext.lineTo(x2,y2);arrowContext.stroke();arrowContext.beginPath();arrowContext.moveTo(x2,y2);arrowContext.lineTo(x2-head*Math.cos(angle-.55),y2-head*Math.sin(angle-.55));arrowContext.lineTo(x2-head*Math.cos(angle+.55),y2-head*Math.sin(angle+.55));arrowContext.closePath();arrowContext.fill();}arrowContext.restore();}
function drawParticles(dt){const{math,screen,dpr}=viewport(),spanX=math.right-math.left,spanY=math.top-math.bottom,step=Math.hypot(spanX,spanY)*.055*settings.particleSpeed;while(particles.length<settings.particleCount)particles.push(newParticle(math));if(particles.length>settings.particleCount)particles.length=settings.particleCount;particleContext.setTransform(dpr,0,0,dpr,0,0);clip(particleContext,screen);particleContext.lineCap='round';particleContext.lineWidth=1.25;particleContext.strokeStyle='rgba(35,190,255,.62)';for(let i=0;i<particles.length;i++){const particle=particles[i],before=toScreen(particle.x,particle.y,math,screen),v=field.model.evaluate(particle.x,particle.y),m=Math.hypot(v[0],v[1]);if(!Number.isFinite(m)||m<1e-10){particles[i]=newParticle(math);continue;}particle.x+=v[0]/m*step*dt;particle.y+=v[1]/m*step*dt;particle.age-=dt;const after=toScreen(particle.x,particle.y,math,screen);particleContext.beginPath();particleContext.moveTo(before.x,before.y);particleContext.lineTo(after.x,after.y);particleContext.stroke();if(particle.age<=0||particle.x<math.left||particle.x>math.right||particle.y<math.bottom||particle.y>math.top)particles[i]=newParticle(math);}particleContext.restore();}
function newParticle(math){return{x:math.left+Math.random()*(math.right-math.left),y:math.bottom+Math.random()*(math.top-math.bottom),age:.8+Math.random()*4};}
function resetParticles(){particles=[];}
function toScreen(x,y,math,screen){return{x:screen.left+(x-math.left)/(math.right-math.left)*screen.width,y:screen.top+(math.top-y)/(math.top-math.bottom)*screen.height};}
function clip(context,screen){context.save();context.beginPath();context.rect(screen.left,screen.top,screen.width,screen.height);context.clip();}
function resize(canvas){const dpr=Math.min(devicePixelRatio||1,2),width=innerWidth,height=innerHeight;if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;}}
