import{compileVectorField}from'../../src/lib/math/expression.js';import{parseDesmosVectorField}from'./core/desmosLatex.js';
const CHANNEL='fieldplay-desmos',canvas=document.createElement('canvas'),status=document.createElement('button');let ctx,state,field,enabled=true,frame=0;
canvas.id='fieldplay-desmos-overlay';status.id='fieldplay-desmos-status';status.type='button';status.title='FieldPlay overlay — Alt+V toggles visibility';status.textContent='FieldPlay: waiting';document.documentElement.append(canvas,status);ctx=canvas.getContext('2d',{alpha:true});
window.addEventListener('message',event=>{if(event.source!==window||event.data?.channel!==CHANNEL||event.data.type!=='state')return;state=event.data.payload;updateField();schedule();});
window.addEventListener('resize',schedule);document.addEventListener('keydown',event=>{if(event.altKey&&event.key.toLowerCase()==='v'){enabled=!enabled;status.dataset.disabled=String(!enabled);schedule();}});status.addEventListener('click',()=>{enabled=!enabled;status.dataset.disabled=String(!enabled);schedule();});
function updateField(){field=null;if(state?.mode==='2d')for(const expression of state.expressions){if(expression.hidden)continue;const parsed=parseDesmosVectorField(expression.latex);if(!parsed)continue;try{field={...parsed,model:compileVectorField(parsed.x,parsed.y)};break;}catch(error){status.textContent=`FieldPlay: ${error.message}`;return;}}status.textContent=field?`FieldPlay: ${field.name}(x,y)`:'FieldPlay: type F(x,y)=(P,Q)';}
function schedule(){if(frame)return;frame=requestAnimationFrame(draw);}
function draw(){frame=0;resize();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);if(!enabled||!field||!state?.bounds)return;const pixel=state.bounds.pixelCoordinates,math=state.bounds.mathCoordinates;if(!pixel||!math)return;const dpr=Math.min(devicePixelRatio||1,2),width=pixel.right-pixel.left,height=pixel.bottom-pixel.top,rows=22,cols=Math.max(10,Math.round(rows*width/height)),cell=Math.min(width/cols,height/rows),maxLength=cell*.72,samples=[];for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=math.left+(i+.5)/cols*(math.right-math.left),y=math.top+(j+.5)/rows*(math.bottom-math.top),v=field.model.evaluate(x,y),m=Math.hypot(v[0],v[1]);if(Number.isFinite(m)&&m>1e-10)samples.push({i,j,v,m});}const magnitudes=samples.map(s=>s.m).sort((a,b)=>a-b),scale=magnitudes[Math.floor(magnitudes.length*.92)]||1;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.lineCap='round';for(const sample of samples){const cx=pixel.left+(sample.i+.5)/cols*width,cy=pixel.top+(sample.j+.5)/rows*height,ux=sample.v[0]/sample.m,uy=-sample.v[1]/sample.m,length=maxLength*(.28+.72*Math.sqrt(Math.min(1,sample.m/scale))),x1=cx-ux*length/2,y1=cy-uy*length/2,x2=cx+ux*length/2,y2=cy+uy*length/2,angle=Math.atan2(y2-y1,x2-x1),head=Math.min(6,length*.3),t=Math.min(1,sample.m/scale);ctx.strokeStyle=`hsla(${195-155*t},92%,${68-15*t}%,.9)`;ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-head*Math.cos(angle-.55),y2-head*Math.sin(angle-.55));ctx.lineTo(x2-head*Math.cos(angle+.55),y2-head*Math.sin(angle+.55));ctx.closePath();ctx.fill();}}
function resize(){const dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;}}
