import{compileExpression,compileVectorField}from'../../src/lib/math/expression.js';
import{contourSegments}from'../../src/lib/math/overlayGeometry.js';
import{parseDesmosContour,parseDesmosSlopeField,parseDesmosVectorField}from'./core/desmosLatex.js';
const CHANNEL='fieldplay-desmos',settings={arrows:true,particles:true,contours:true,particleCount:1400,particleSpeed:1,contourLevels:9};
const arrowCanvas=makeCanvas('fieldplay-desmos-overlay'),particleCanvas=makeCanvas('fieldplay-desmos-particles'),arrowContext=arrowCanvas.getContext('2d',{alpha:true}),particleContext=particleCanvas.getContext('2d',{alpha:true}),status=document.createElement('button'),menu=document.createElement('div');
let state,field,scalar,frame=0,lastTime=performance.now(),particles=[],staticDirty=true,lastExpressions='';
status.id='fieldplay-desmos-status';status.type='button';status.title='FieldPlay controls';status.setAttribute('aria-controls','fieldplay-desmos-menu');status.setAttribute('aria-expanded','false');status.textContent='FieldPlay: waiting';
menu.id='fieldplay-desmos-menu';menu.setAttribute('role','dialog');menu.setAttribute('aria-label','FieldPlay overlay controls');menu.hidden=true;menu.innerHTML=`<div class="fieldplay-title">FieldPlay overlay</div><label><input type="checkbox" data-setting="arrows" checked> Vector arrows</label><label><input type="checkbox" data-setting="particles" checked> Flow particles</label><label><input type="checkbox" data-setting="contours" checked> Contour lines</label><label class="fieldplay-range">Particles <input aria-label="Particle count" type="range" data-setting="particleCount" min="200" max="5000" step="200" value="1400"><output>1400</output></label><label class="fieldplay-range">Speed <input aria-label="Particle speed" type="range" data-setting="particleSpeed" min="0.2" max="2.5" step="0.1" value="1"><output>1.0×</output></label><label class="fieldplay-range">Contours <input aria-label="Contour levels" type="range" data-setting="contourLevels" min="3" max="20" step="1" value="9"><output>9</output></label><div class="fieldplay-hint">contour f=x²+y² · Alt+V toggles flow</div>`;
document.documentElement.append(arrowCanvas,particleCanvas,status,menu);
chrome.storage?.local.get(settings,saved=>{Object.assign(settings,saved);syncControls();resetParticles();schedule();});
window.addEventListener('message',event=>{if(event.source!==window||event.data?.channel!==CHANNEL||event.data.type!=='state')return;state=event.data.payload;const key=JSON.stringify(state.expressions.map(x=>[x.id,x.latex,x.hidden]));if(key!==lastExpressions){lastExpressions=key;updateVisualizations();resetParticles();}staticDirty=true;schedule();});
window.addEventListener('resize',schedule);document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!menu.hidden){setMenuOpen(false);status.focus();return;}if(event.altKey&&event.key.toLowerCase()==='v'){const enabled=settings.arrows||settings.particles;settings.arrows=!enabled;settings.particles=!enabled;saveSettings();syncControls();schedule();}});
status.addEventListener('click',()=>setMenuOpen(menu.hidden));document.addEventListener('pointerdown',event=>{if(!menu.hidden&&!menu.contains(event.target)&&event.target!==status)setMenuOpen(false);});
menu.addEventListener('input',event=>{const key=event.target.dataset.setting;if(!key)return;settings[key]=event.target.type==='checkbox'?event.target.checked:Number(event.target.value);if(key==='particleCount')resetParticles();if(key==='arrows'||key==='contours'||key==='contourLevels')staticDirty=true;saveSettings();syncControls();schedule();});
function makeCanvas(id){const element=document.createElement('canvas');element.id=id;return element;}
function setMenuOpen(open){menu.hidden=!open;status.setAttribute('aria-expanded',String(open));}
function saveSettings(){chrome.storage?.local.set(settings);}
function syncControls(){for(const input of menu.querySelectorAll('[data-setting]')){const key=input.dataset.setting;if(input.type==='checkbox')input.checked=settings[key];else input.value=settings[key];const output=input.parentElement.querySelector('output');if(output)output.textContent=key==='particleSpeed'?`${Number(settings[key]).toFixed(1)}×`:String(settings[key]);}status.dataset.disabled=String(!settings.arrows&&!settings.particles&&!settings.contours);}
function updateVisualizations(){field=null;scalar=null;let error='';if(state?.mode==='2d')for(const expression of state.expressions){if(expression.hidden)continue;try{if(!field){const parsed=parseDesmosVectorField(expression.latex)||parseDesmosSlopeField(expression.latex);if(parsed)field={...parsed,model:compileVectorField(parsed.x,parsed.y)};}if(!scalar){const parsed=parseDesmosContour(expression.latex);if(parsed)scalar={...parsed,model:compileExpression(parsed.expression)};}}catch(reason){error=reason.message;}}status.textContent=error?`FieldPlay: ${error}`:field&&scalar?`FieldPlay: ${field.name} + contours`:field?`FieldPlay: ${field.name}${field.kind==='slope-field'?'':'(x,y)'}`:scalar?`FieldPlay: contour ${scalar.name}`:'FieldPlay: vec F=<<P,Q>> · contour f=g(x,y)';staticDirty=true;}
function schedule(){if(!frame)frame=requestAnimationFrame(draw);}
function draw(now){frame=0;if(document.hidden)return;const dt=Math.min(.04,Math.max(0,(now-lastTime)/1000));lastTime=now;if(resize(arrowCanvas))staticDirty=true;resize(particleCanvas);if(staticDirty){clear(arrowContext,arrowCanvas);if(state?.bounds&&state?.viewport){if(scalar&&settings.contours)drawContours();if(field&&settings.arrows)drawArrows();}staticDirty=false;}clear(particleContext,particleCanvas);if(field&&settings.particles&&state?.bounds&&state?.viewport)drawParticles(dt);if(field&&settings.particles)schedule();}
function clear(context,canvas){context.setTransform(1,0,0,1,0,0);context.clearRect(0,0,canvas.width,canvas.height);}
function viewport(){const math=state.bounds.mathCoordinates,screen=state.viewport;return{math,screen,dpr:Math.min(devicePixelRatio||1,2),width:screen.width,height:screen.height};}
function drawArrows(){const{math,screen,dpr,width,height}=viewport(),rows=Math.max(12,Math.round(height/40)),cols=Math.max(10,Math.round(width/40)),cell=Math.min(width/cols,height/rows),maxLength=cell*.72,samples=[];for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=math.left+(i+.5)/cols*(math.right-math.left),y=math.top+(j+.5)/rows*(math.bottom-math.top),v=field.model.evaluate(x,y),m=Math.hypot(v[0],v[1]);if(Number.isFinite(m)&&m>1e-10)samples.push({i,j,v,m});}const magnitudes=samples.map(sample=>sample.m).sort((a,b)=>a-b),scale=magnitudes[Math.floor(magnitudes.length*.92)]||1;arrowContext.setTransform(dpr,0,0,dpr,0,0);clip(arrowContext,screen);arrowContext.lineCap='round';for(const sample of samples){const cx=screen.left+(sample.i+.5)/cols*width,cy=screen.top+(sample.j+.5)/rows*height,ux=sample.v[0]/sample.m,uy=-sample.v[1]/sample.m,length=maxLength*(.28+.72*Math.sqrt(Math.min(1,sample.m/scale))),x1=cx-ux*length/2,y1=cy-uy*length/2,x2=cx+ux*length/2,y2=cy+uy*length/2,angle=Math.atan2(y2-y1,x2-x1),head=Math.min(6,length*.3),t=Math.min(1,sample.m/scale);arrowContext.strokeStyle=`hsla(${195-155*t},92%,${68-15*t}%,.88)`;arrowContext.fillStyle=arrowContext.strokeStyle;arrowContext.lineWidth=1.4;arrowContext.beginPath();arrowContext.moveTo(x1,y1);arrowContext.lineTo(x2,y2);arrowContext.stroke();arrowContext.beginPath();arrowContext.moveTo(x2,y2);arrowContext.lineTo(x2-head*Math.cos(angle-.55),y2-head*Math.sin(angle-.55));arrowContext.lineTo(x2-head*Math.cos(angle+.55),y2-head*Math.sin(angle+.55));arrowContext.closePath();arrowContext.fill();}arrowContext.restore();}
function drawContours(){const{math,screen,dpr,width,height}=viewport(),cols=Math.max(32,Math.min(72,Math.round(width/20))),rows=Math.max(24,Math.min(56,Math.round(height/20))),values=[];for(let j=0;j<=rows;j++)for(let i=0;i<=cols;i++){const x=math.left+i/cols*(math.right-math.left),y=math.top+j/rows*(math.bottom-math.top);values.push(scalar.model.evaluate(x,y));}const finite=values.filter(Number.isFinite).sort((a,b)=>a-b);if(finite.length<4)return;const low=finite[Math.floor(finite.length*.04)],high=finite[Math.floor(finite.length*.96)];if(!Number.isFinite(low)||!Number.isFinite(high)||Math.abs(high-low)<1e-12)return;arrowContext.setTransform(dpr,0,0,dpr,0,0);clip(arrowContext,screen);arrowContext.lineWidth=1.15;for(let index=1;index<=settings.contourLevels;index++){const t=index/(settings.contourLevels+1),level=low+t*(high-low),segments=contourSegments(values,cols,rows,level,width,height);arrowContext.strokeStyle=`hsla(${275-90*t},88%,${68-8*t}%,.72)`;arrowContext.beginPath();for(const segment of segments){arrowContext.moveTo(screen.left+segment[0][0],screen.top+segment[0][1]);arrowContext.lineTo(screen.left+segment[1][0],screen.top+segment[1][1]);}arrowContext.stroke();}arrowContext.restore();}
function drawParticles(dt){const{math,screen,dpr}=viewport(),spanX=math.right-math.left,spanY=math.top-math.bottom,step=Math.hypot(spanX,spanY)*.055*settings.particleSpeed;while(particles.length<settings.particleCount)particles.push(newParticle(math));if(particles.length>settings.particleCount)particles.length=settings.particleCount;particleContext.setTransform(dpr,0,0,dpr,0,0);clip(particleContext,screen);particleContext.lineCap='round';particleContext.lineWidth=1.25;particleContext.strokeStyle='rgba(35,190,255,.62)';for(let i=0;i<particles.length;i++){const particle=particles[i],before=toScreen(particle.x,particle.y,math,screen),v=field.model.evaluate(particle.x,particle.y),m=Math.hypot(v[0],v[1]);if(!Number.isFinite(m)||m<1e-10){particles[i]=newParticle(math);continue;}particle.x+=v[0]/m*step*dt;particle.y+=v[1]/m*step*dt;particle.age-=dt;const after=toScreen(particle.x,particle.y,math,screen);particleContext.beginPath();particleContext.moveTo(before.x,before.y);particleContext.lineTo(after.x,after.y);particleContext.stroke();if(particle.age<=0||particle.x<math.left||particle.x>math.right||particle.y<math.bottom||particle.y>math.top)particles[i]=newParticle(math);}particleContext.restore();}
function newParticle(math){return{x:math.left+Math.random()*(math.right-math.left),y:math.bottom+Math.random()*(math.top-math.bottom),age:.8+Math.random()*4};}
function resetParticles(){particles=[];}
function toScreen(x,y,math,screen){return{x:screen.left+(x-math.left)/(math.right-math.left)*screen.width,y:screen.top+(math.top-y)/(math.top-math.bottom)*screen.height};}
function clip(context,screen){context.save();context.beginPath();context.rect(screen.left,screen.top,screen.width,screen.height);context.clip();}
function resize(canvas){const dpr=Math.min(devicePixelRatio||1,2),width=innerWidth,height=innerHeight,targetWidth=Math.round(width*dpr),targetHeight=Math.round(height*dpr);if(canvas.width===targetWidth&&canvas.height===targetHeight)return false;canvas.width=targetWidth;canvas.height=targetHeight;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;return true;}
