import{paletteStops}from'../../src/lib/colorPalettes.js';

export class GpuParticles{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:false});this.count=0;this.read=0;this.buffers=[];this.updateProgram=null;this.drawProgram=null;this.copyProgram=null;this.fieldCode='';this.palette='neon';this.seedBoundsKey='';this.trailTextures=[];this.trailFramebuffers=[];this.trailRead=0;this.trailSize='';this.viewKey='';if(this.gl)this.copyProgram=this.makeCopy();}
  get available(){return Boolean(this.gl);}
  configure(field,count,palette,bounds){if(!this.gl)return false;const code=field?.code||'',boundsKey=particleBoundsKey(bounds),fieldChanged=code!==this.fieldCode;if(fieldChanged){this.fieldCode=code;if(this.updateProgram)this.gl.deleteProgram(this.updateProgram);if(this.drawProgram)this.gl.deleteProgram(this.drawProgram);this.updateProgram=this.makeUpdate(code);this.drawProgram=this.makeDraw(code,palette);this.palette=palette;this.invalidateTrails();}else if(palette!==this.palette){if(this.drawProgram)this.gl.deleteProgram(this.drawProgram);this.drawProgram=this.makeDraw(code,palette);this.palette=palette;this.invalidateTrails();}if(fieldChanged||count!==this.count||boundsKey!==this.seedBoundsKey){this.seedBoundsKey=boundsKey;this.seed(count,bounds);this.invalidateTrails();}return Boolean(this.updateProgram&&this.drawProgram&&this.copyProgram);}
  seed(count,bounds){const gl=this.gl,data=new Float32Array(count*4),left=bounds?.left??-1,right=bounds?.right??1,bottom=bounds?.bottom??-1,top=bounds?.top??1;for(let i=0;i<count;i++){data[i*4]=left+Math.random()*(right-left);data[i*4+1]=bottom+Math.random()*(top-bottom);data[i*4+2]=Math.random()*8;data[i*4+3]=Math.random();}for(const buffer of this.buffers)gl.deleteBuffer(buffer);this.buffers=[gl.createBuffer(),gl.createBuffer()];for(const buffer of this.buffers){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_COPY);}this.count=count;this.read=0;}
  render({bounds,screen,dpr,dt,speed,pointSize,time,trailPersistence=.94}){const gl=this.gl;if(!gl||!this.updateProgram||!this.drawProgram||!this.count)return;this.ensureTrails();const minX=bounds.left,maxX=bounds.right,minY=bounds.bottom,maxY=bounds.top,diagonal=Math.hypot(maxX-minX,maxY-minY),write=1-this.read,viewKey=[minX,maxX,minY,maxY,screen.left,screen.top,screen.width,screen.height].map(value=>Number(value).toPrecision(6)).join('|');if(this.viewKey&&viewKey!==this.viewKey)this.clearTrails();this.viewKey=viewKey;
    gl.useProgram(this.updateProgram);gl.enable(gl.RASTERIZER_DISCARD);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[this.read]);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,0,0);uniform4(gl,this.updateProgram,'u_bounds',[minX,maxX,minY,maxY]);uniform1(gl,this.updateProgram,'u_dt',dt);uniform1(gl,this.updateProgram,'u_speed',speed);uniform1(gl,this.updateProgram,'u_max_step',diagonal*.018);uniform1(gl,this.updateProgram,'frame',time);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,this.buffers[write]);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,this.count);gl.endTransformFeedback();gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,null);gl.disable(gl.RASTERIZER_DISCARD);
    const trailWrite=1-this.trailRead;gl.bindFramebuffer(gl.FRAMEBUFFER,this.trailFramebuffers[trailWrite]);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.disable(gl.BLEND);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);this.copy(this.trailTextures[this.trailRead],trailPersistence);gl.useProgram(this.drawProgram);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[write]);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,4,gl.FLOAT,false,0,0);uniform4(gl,this.drawProgram,'u_bounds',[minX,maxX,minY,maxY]);uniform4(gl,this.drawProgram,'u_screen',[screen.left*dpr,screen.top*dpr,screen.width*dpr,screen.height*dpr]);uniform2(gl,this.drawProgram,'u_canvas',[this.canvas.width,this.canvas.height]);uniform1(gl,this.drawProgram,'u_point_size',pointSize*dpr);uniform1(gl,this.drawProgram,'frame',time);gl.enable(gl.SCISSOR_TEST);gl.scissor(Math.round(screen.left*dpr),Math.round(this.canvas.height-(screen.top+screen.height)*dpr),Math.round(screen.width*dpr),Math.round(screen.height*dpr));gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.POINTS,0,this.count);gl.disable(gl.SCISSOR_TEST);gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.disable(gl.BLEND);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);this.copy(this.trailTextures[trailWrite],1);this.read=write;this.trailRead=trailWrite;}
  clear(){const gl=this.gl;if(!gl)return;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);}
  invalidateTrails(){this.viewKey='';this.clearTrails();}
  ensureTrails(){const gl=this.gl,key=`${this.canvas.width}x${this.canvas.height}`;if(key===this.trailSize)return;for(const texture of this.trailTextures)gl.deleteTexture(texture);for(const framebuffer of this.trailFramebuffers)gl.deleteFramebuffer(framebuffer);this.trailTextures=[];this.trailFramebuffers=[];for(let i=0;i<2;i++){const texture=gl.createTexture(),framebuffer=gl.createFramebuffer();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,this.canvas.width,this.canvas.height,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);this.trailTextures.push(texture);this.trailFramebuffers.push(framebuffer);}this.trailSize=key;this.trailRead=0;this.clearTrails();gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
  clearTrails(){const gl=this.gl;if(!gl||!this.trailFramebuffers.length)return;for(const framebuffer of this.trailFramebuffers){gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);}gl.bindFramebuffer(gl.FRAMEBUFFER,null);}
  copy(texture,opacity){const gl=this.gl;gl.useProgram(this.copyProgram);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(gl.getUniformLocation(this.copyProgram,'u_texture'),0);uniform1(gl,this.copyProgram,'u_opacity',opacity);gl.drawArrays(gl.TRIANGLES,0,3);}
  makeUpdate(fieldCode){return program(this.gl,`#version 300 es\nprecision highp float;layout(location=0)in vec4 a_state;uniform vec4 u_bounds;uniform float u_dt,u_speed,u_max_step,frame;out vec4 v_state;${fieldCode}\nfloat hash(float n){return fract(sin(n)*43758.5453123);}vec2 flow(vec2 p){vec2 v=get_velocity(p);return all(equal(v,v))&&all(lessThan(abs(v),vec2(1e18)))?v:vec2(0);}void main(){vec2 p=a_state.xy;float age=a_state.z+u_dt;float seed=a_state.w;float h=u_dt*u_speed;vec2 k1=flow(p),k2=flow(p+k1*h*.5),k3=flow(p+k2*h*.5),k4=flow(p+k3*h);vec2 delta=h*(k1+2.0*k2+2.0*k3+k4)/6.0;float d=length(delta);if(d>u_max_step)delta*=u_max_step/d;p+=delta;vec2 span=u_bounds.yw-u_bounds.xz;p=u_bounds.xz+mod(mod(p-u_bounds.xz,span)+span,span);float life=mix(2.0,6.0,seed);float chance=hash(float(gl_VertexID)*12.9898+floor(frame*30.0)*78.233);bool reset=age>life&&chance<u_dt*.45;if(reset){float id=float(gl_VertexID)+floor(frame*1000.0);p=vec2(mix(u_bounds.x,u_bounds.y,hash(id+seed*31.0)),mix(u_bounds.z,u_bounds.w,hash(id+19.7+seed*47.0)));age=0.0;seed=hash(id+71.3);}v_state=vec4(p,age,seed);}`,`#version 300 es\nprecision highp float;void main(){}`,['v_state']);}
  makeDraw(fieldCode,palette){return program(this.gl,`#version 300 es\nprecision highp float;layout(location=0)in vec4 a_state;uniform vec4 u_bounds,u_screen;uniform vec2 u_canvas;uniform float u_point_size,frame;out vec4 v_color;${fieldCode}\n${paletteFunction(palette)}void main(){vec2 p=a_state.xy;vec2 unit=(p-vec2(u_bounds.x,u_bounds.z))/vec2(u_bounds.y-u_bounds.x,u_bounds.w-u_bounds.z);vec2 pixel=u_screen.xy+vec2(unit.x,1.0-unit.y)*u_screen.zw;vec2 clip=vec2(pixel.x/u_canvas.x*2.0-1.0,1.0-pixel.y/u_canvas.y*2.0);gl_Position=vec4(clip,0,1);gl_PointSize=u_point_size;vec2 velocity=get_velocity(p);float t=${palette==='rainbow'?'(atan(velocity.y,velocity.x)+3.14159265)/6.2831853':'1.0-exp(-length(velocity)*0.18)'};v_color=vec4(studio_palette(clamp(t,0.0,1.0)),0.38);}`,`#version 300 es\nprecision highp float;in vec4 v_color;out vec4 color;void main(){float a=1.0-smoothstep(0.08,0.5,length(gl_PointCoord-0.5));color=vec4(v_color.rgb,v_color.a*a);}`);}
  makeCopy(){return program(this.gl,`#version 300 es\nprecision highp float;out vec2 uv;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);uv=p*.5;gl_Position=vec4(p*2.0-1.0,0,1);}`,`#version 300 es\nprecision highp float;uniform sampler2D u_texture;uniform float u_opacity;in vec2 uv;out vec4 color;void main(){color=texture(u_texture,uv)*u_opacity;}`);}
}

function program(gl,vertexSource,fragmentSource,varyings){const vertex=shader(gl,gl.VERTEX_SHADER,vertexSource),fragment=shader(gl,gl.FRAGMENT_SHADER,fragmentSource);if(!vertex||!fragment)return null;const result=gl.createProgram();gl.attachShader(result,vertex);gl.attachShader(result,fragment);if(varyings)gl.transformFeedbackVaryings(result,varyings,gl.SEPARATE_ATTRIBS);gl.linkProgram(result);if(!gl.getProgramParameter(result,gl.LINK_STATUS)){console.warn('FieldPlay GPU shader:',gl.getProgramInfoLog(result));gl.deleteProgram(result);return null;}return result;}
function shader(gl,type,source){const result=gl.createShader(type);gl.shaderSource(result,source);gl.compileShader(result);if(!gl.getShaderParameter(result,gl.COMPILE_STATUS)){console.warn('FieldPlay GPU shader:',gl.getShaderInfoLog(result));gl.deleteShader(result);return null;}return result;}
function uniform1(gl,p,name,value){gl.uniform1f(gl.getUniformLocation(p,name),value);}function uniform2(gl,p,name,value){gl.uniform2fv(gl.getUniformLocation(p,name),value);}function uniform4(gl,p,name,value){gl.uniform4fv(gl.getUniformLocation(p,name),value);}
function paletteFunction(name){const stops=paletteStops(name),colors=stops.map(hex=>{const h=hex.slice(1);return[0,2,4].map(i=>(parseInt(h.slice(i,i+2),16)/255).toFixed(5));});if(colors.length===1)return`vec3 studio_palette(float t){return vec3(${colors[0].join(',')});}`;let body='';for(let i=0;i<colors.length-1;i++){const high=(i+1)/(colors.length-1),low=i/(colors.length-1);body+=`${i?'else ':''}if(t<=${high.toFixed(6)})return mix(vec3(${colors[i].join(',')}),vec3(${colors[i+1].join(',')}),clamp((t-${low.toFixed(6)})/${(high-low).toFixed(6)},0.0,1.0));`;}return`vec3 studio_palette(float t){${body}return vec3(${colors.at(-1).join(',')});}`;}
export function particleBoundsKey(bounds){if(!bounds)return'';return[bounds.left,bounds.right,bounds.bottom,bounds.top].map(value=>Number(value).toPrecision(6)).join('|');}
