import{paletteStops}from'../../src/lib/colorPalettes.js';

export class GpuParticles{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2',{alpha:true,antialias:false,premultipliedAlpha:false});this.count=0;this.read=0;this.buffers=[];this.updateProgram=null;this.drawProgram=null;this.fieldCode='';this.palette='neon';}
  get available(){return Boolean(this.gl);}
  configure(field,count,palette,bounds){if(!this.gl)return false;const code=field?.code||'';if(code!==this.fieldCode){this.fieldCode=code;if(this.updateProgram)this.gl.deleteProgram(this.updateProgram);if(this.drawProgram)this.gl.deleteProgram(this.drawProgram);this.updateProgram=this.makeUpdate(code);this.drawProgram=this.makeDraw(code,palette);this.palette=palette;}else if(palette!==this.palette){if(this.drawProgram)this.gl.deleteProgram(this.drawProgram);this.drawProgram=this.makeDraw(code,palette);this.palette=palette;}if(count!==this.count)this.seed(count,bounds);return Boolean(this.updateProgram&&this.drawProgram);}
  seed(count,bounds){const gl=this.gl,data=new Float32Array(count*2),left=bounds?.left??-1,right=bounds?.right??1,bottom=bounds?.bottom??-1,top=bounds?.top??1;for(let i=0;i<count;i++){data[i*2]=left+Math.random()*(right-left);data[i*2+1]=bottom+Math.random()*(top-bottom);}for(const buffer of this.buffers)gl.deleteBuffer(buffer);this.buffers=[gl.createBuffer(),gl.createBuffer()];for(const buffer of this.buffers){gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_COPY);}this.count=count;this.read=0;}
  render({bounds,screen,dpr,dt,speed,pointSize,time}){const gl=this.gl;if(!gl||!this.updateProgram||!this.drawProgram||!this.count)return;const minX=bounds.left,maxX=bounds.right,minY=bounds.bottom,maxY=bounds.top,diagonal=Math.hypot(maxX-minX,maxY-minY),write=1-this.read;
    gl.useProgram(this.updateProgram);gl.enable(gl.RASTERIZER_DISCARD);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[this.read]);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);uniform4(gl,this.updateProgram,'u_bounds',[minX,maxX,minY,maxY]);uniform1(gl,this.updateProgram,'u_dt',dt);uniform1(gl,this.updateProgram,'u_step',diagonal*.055*speed);uniform1(gl,this.updateProgram,'frame',time);gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,this.buffers[write]);gl.beginTransformFeedback(gl.POINTS);gl.drawArrays(gl.POINTS,0,this.count);gl.endTransformFeedback();gl.bindBufferBase(gl.TRANSFORM_FEEDBACK_BUFFER,0,null);gl.disable(gl.RASTERIZER_DISCARD);
    gl.useProgram(this.drawProgram);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffers[write]);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);uniform4(gl,this.drawProgram,'u_bounds',[minX,maxX,minY,maxY]);uniform4(gl,this.drawProgram,'u_screen',[screen.left*dpr,screen.top*dpr,screen.width*dpr,screen.height*dpr]);uniform2(gl,this.drawProgram,'u_canvas',[this.canvas.width,this.canvas.height]);uniform1(gl,this.drawProgram,'u_point_size',pointSize*dpr);uniform1(gl,this.drawProgram,'frame',time);gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.enable(gl.SCISSOR_TEST);gl.scissor(Math.round(screen.left*dpr),Math.round(this.canvas.height-(screen.top+screen.height)*dpr),Math.round(screen.width*dpr),Math.round(screen.height*dpr));gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.drawArrays(gl.POINTS,0,this.count);gl.disable(gl.SCISSOR_TEST);this.read=write;}
  clear(){const gl=this.gl;if(!gl)return;gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);}
  makeUpdate(fieldCode){return program(this.gl,`#version 300 es\nprecision highp float;layout(location=0)in vec2 a_position;uniform vec4 u_bounds;uniform float u_dt,u_step,frame;out vec2 v_position;${fieldCode}\nfloat hash(float n){return fract(sin(n)*43758.5453123);}void main(){vec2 p=a_position;vec2 v=get_velocity(p);float m=length(v);if(m>1e-10&&!isnan(m)&&!isinf(m))p+=v/m*u_step*u_dt;bool outOfBounds=p.x<u_bounds.x||p.x>u_bounds.y||p.y<u_bounds.z||p.y>u_bounds.w;if(outOfBounds){float id=float(gl_VertexID)+frame*17.0;p=vec2(mix(u_bounds.x,u_bounds.y,hash(id)),mix(u_bounds.z,u_bounds.w,hash(id+19.7)));}v_position=p;}`,`#version 300 es\nprecision highp float;void main(){}`,['v_position']);}
  makeDraw(fieldCode,palette){return program(this.gl,`#version 300 es\nprecision highp float;layout(location=0)in vec2 a_position;uniform vec4 u_bounds,u_screen;uniform vec2 u_canvas;uniform float u_point_size,frame;out vec4 v_color;${fieldCode}\n${paletteFunction(palette)}void main(){vec2 unit=(a_position-vec2(u_bounds.x,u_bounds.z))/vec2(u_bounds.y-u_bounds.x,u_bounds.w-u_bounds.z);vec2 pixel=u_screen.xy+vec2(unit.x,1.0-unit.y)*u_screen.zw;vec2 clip=vec2(pixel.x/u_canvas.x*2.0-1.0,1.0-pixel.y/u_canvas.y*2.0);gl_Position=vec4(clip,0,1);gl_PointSize=u_point_size;vec2 velocity=get_velocity(a_position);float t=${palette==='rainbow'?'(atan(velocity.y,velocity.x)+3.14159265)/6.2831853':'1.0-exp(-length(velocity)*0.18)'};v_color=vec4(studio_palette(clamp(t,0.0,1.0)),0.72);}`,`#version 300 es\nprecision highp float;in vec4 v_color;out vec4 color;void main(){vec2 q=gl_PointCoord-0.5;float a=1.0-smoothstep(0.08,0.5,length(q));color=vec4(v_color.rgb,v_color.a*a);}`);}
}

function program(gl,vertexSource,fragmentSource,varyings){const vertex=shader(gl,gl.VERTEX_SHADER,vertexSource),fragment=shader(gl,gl.FRAGMENT_SHADER,fragmentSource);if(!vertex||!fragment)return null;const result=gl.createProgram();gl.attachShader(result,vertex);gl.attachShader(result,fragment);if(varyings)gl.transformFeedbackVaryings(result,varyings,gl.SEPARATE_ATTRIBS);gl.linkProgram(result);if(!gl.getProgramParameter(result,gl.LINK_STATUS)){console.warn('FieldPlay GPU shader:',gl.getProgramInfoLog(result));gl.deleteProgram(result);return null;}return result;}
function shader(gl,type,source){const result=gl.createShader(type);gl.shaderSource(result,source);gl.compileShader(result);if(!gl.getShaderParameter(result,gl.COMPILE_STATUS)){console.warn('FieldPlay GPU shader:',gl.getShaderInfoLog(result));gl.deleteShader(result);return null;}return result;}
function uniform1(gl,p,name,value){gl.uniform1f(gl.getUniformLocation(p,name),value);}function uniform2(gl,p,name,value){gl.uniform2fv(gl.getUniformLocation(p,name),value);}function uniform4(gl,p,name,value){gl.uniform4fv(gl.getUniformLocation(p,name),value);}
function paletteFunction(name){const stops=paletteStops(name),colors=stops.map(hex=>{const h=hex.slice(1);return[0,2,4].map(i=>(parseInt(h.slice(i,i+2),16)/255).toFixed(5));});if(colors.length===1)return`vec3 studio_palette(float t){return vec3(${colors[0].join(',')});}`;let body='';for(let i=0;i<colors.length-1;i++){const high=(i+1)/(colors.length-1),low=i/(colors.length-1);body+=`${i?'else ':''}if(t<=${high.toFixed(6)})return mix(vec3(${colors[i].join(',')}),vec3(${colors[i+1].join(',')}),clamp((t-${low.toFixed(6)})/${(high-low).toFixed(6)},0.0,1.0));`;}return`vec3 studio_palette(float t){${body}return vec3(${colors.at(-1).join(',')});}`;}
