import{normalizeDesmosLatex,splitTopLevel}from'./core/desmosLatex.js';
import{differentiateExpression,integrateExpression,simplifyExpression,solvePolynomial,toLatex}from'./core/symbolic.js';
const CHANNEL='fieldplay-desmos';let vectorBracketOpen=false,suppressSecondClose=false,vectorEntry=null,lastSnapshot='',expressions=[];

boot();
function boot(){if(!window.Calc){setTimeout(boot,100);return;}refreshExpressions();window.Calc.observeEvent?.('change',refreshExpressions);window.addEventListener('keydown',onKeyDown,true);window.postMessage({channel:CHANNEL,type:'ready'},location.origin);trackViewport();}
function refreshExpressions(){expressions=(window.Calc.getExpressions?.()||[]).map(({id,latex,hidden,color})=>({id,latex,hidden,color}));emitState();}
function trackViewport(){emitState();requestAnimationFrame(trackViewport);}
function emitState(){const bounds=window.Calc.graphpaperBounds,viewport=getGraphViewport(),snapshot=JSON.stringify([bounds,viewport,expressions.map(x=>[x.id,x.latex,x.hidden])]);if(snapshot===lastSnapshot)return;lastSnapshot=snapshot;window.postMessage({channel:CHANNEL,type:'state',payload:{mode:location.pathname.startsWith('/3d')?'3d':'2d',bounds,viewport,expressions}},location.origin);}
function getGraphViewport(){const candidates=[...document.querySelectorAll('.dcg-graph-inner,.dcg-graphpaper')];let best=null;for(const element of candidates){const rect=element.getBoundingClientRect();if(rect.width<100||rect.height<100)continue;if(!best||rect.width*rect.height>best.width*best.height)best=rect;}return best?{left:best.left,top:best.top,right:best.right,bottom:best.bottom,width:best.width,height:best.height}:null;}
function onKeyDown(event){
  const focused=window.Calc.focusedMathQuill?.mq;if(!focused)return;const latex=focused.latex();
  if(event.key==='Enter'){const result=runSymbolicCommand(latex);if(result!==null){focused.latex(result);focused.focus();stop(event);return;}}
  if(vectorEntry&&latex!==vectorEntry.rendered)vectorEntry=null;
  if(vectorEntry){if(/^[A-Za-z0-9]$/.test(event.key)){vectorEntry.name+=event.key;renderVectorEntry(focused);stop(event);return;}vectorEntry=null;if(event.key===' '){stop(event);return;}}
  if(event.key==='<'&&latex.endsWith('<')){replaceWithPairedAngles(focused,latex.slice(0,-1));stop(event);return;}
  if(event.key==='>'&&vectorBracketOpen){focused.keystroke('Right');vectorBracketOpen=false;suppressSecondClose=true;stop(event);return;}
  if(event.key==='>'&&suppressSecondClose){suppressSecondClose=false;stop(event);return;}
  const vectorMatch=/(?:^|[^A-Za-z])vec$/.exec(latex);if(vectorMatch&&(/^[A-Za-z]$/.test(event.key)||event.key===' ')){vectorEntry={base:latex.slice(0,-3),name:event.key===' '?'':event.key,rendered:latex};if(vectorEntry.name)renderVectorEntry(focused);stop(event);return;}
  if(event.key!==' ')return;
  const templates=['diff','ddx','ddy','simp','int','solve','px','py'];for(const command of templates)if(latex.endsWith(command)){insertCommandTemplate(focused,latex.slice(0,-command.length),command);stop(event);return;}
  const keywords=[['differentiate','\\operatorname{differentiate}'],['simplify','\\operatorname{simplify}'],['integrate','\\operatorname{integrate}'],['derivative','\\operatorname{derivative}'],['transform','\\operatorname{transform}'],['contour','\\operatorname{contour}\\ '],['laplacian','\\nabla^2\\ '],['surfaceint','\\iint_S '],['tripleint','\\iiint '],['lineint','\\int_C '],['magnitude','\\operatorname{magnitude}'],['partial','\\partial '],['grad','\\nabla\\ '],['curl','\\nabla\\times '],['div','\\nabla\\cdot '],['oint','\\oint ']];for(const[key,replacement]of keywords)if(latex.endsWith(key)){focused.latex(`${latex.slice(0,-key.length)}${replacement}`);focused.focus();stop(event);return;}
  const match=/(?:^|[^A-Za-z])(hat|bar)$/.exec(latex);if(!match)return;const base=latex.slice(0,-match[1].length);focused.latex(`${base}\\${match[1]}{}`);focused.focus();focused.keystroke('Left');stop(event);
}
function insertCommandTemplate(focused,base,command){focused.latex(`${base}\\operatorname{${command}}\\left(\\right)`);focused.focus();focused.keystroke('Left');}
function runSymbolicCommand(latex){try{const normalized=normalizeDesmosLatex(latex),match=/^(simplify|simp|differentiate|derivative|diff|ddx|ddy|partial|px|py|integrate|int|solve|d)\((.*)\)$/.exec(normalized);if(!match)return null;const command=match[1],args=splitTopLevel(match[2],',');if(command==='d'&&args.length===3)return`\\frac{d^{${args[1]}}}{d${args[0]}^{${args[1]}}}\\left(${toLatex(args[2])}\\right)`;if((command==='simplify'||command==='simp')&&args.length===1)return toLatex(simplifyExpression(args[0]));if(command==='ddx'&&args.length===1)return toLatex(differentiateExpression(args[0],'x'));if(command==='ddy'&&args.length===1)return toLatex(differentiateExpression(args[0],'y'));if((command==='px'||command==='py')&&args.length===1)return toLatex(differentiateExpression(args[0],command[1]));if(command==='diff'){if(args.length===1)return toLatex(differentiateExpression(args[0],'x'));if(args.length===2&&/^\d+$/.test(args[1]))return toLatex(differentiateExpression(args[0],'x',Number(args[1])));if(args.length===2)return toLatex(differentiateExpression(args[1],args[0]));}if((command==='differentiate'||command==='derivative')&&(args.length===2||args.length===3)){const[variable,second,third]=args,order=third?Number(second):1,expression=third||second;return toLatex(differentiateExpression(expression,variable,order));}if(command==='partial'&&args.length>=2){let expression=args.at(-1);for(const variable of args.slice(0,-1))expression=differentiateExpression(expression,variable);return toLatex(expression);}if((command==='integrate'&&args.length===2)||(command==='int'&&args.length===1)){const variable=command==='int'?'x':args[0],expression=command==='int'?args[0]:args[1];return`${toLatex(integrateExpression(expression,variable))}+C`;}if(command==='solve'&&(args.length===1||args.length===2)){const variable=args.length===1?'x':args[0],equation=args.at(-1),roots=solvePolynomial(equation,variable);return roots==='all'?`${variable}\\in\\mathbb{R}`:roots.length?`${variable}=\\left[${roots.join(',')}\\right]`:'\\varnothing';}}catch(error){console.warn('FieldPlay symbolic:',error.message);window.postMessage({channel:CHANNEL,type:'notice',payload:`Symbolic math: ${error.message}`},location.origin);return latex;}return null;}
function renderVectorEntry(focused){focused.latex(`${vectorEntry.base}\\overrightarrow{${vectorEntry.name}}`);focused.focus();vectorEntry.rendered=focused.latex();}
function replaceWithPairedAngles(focused,base){focused.latex(`${base}\\left\\langle\\right\\rangle`);focused.focus();focused.keystroke('Left');vectorBracketOpen=true;suppressSecondClose=false;}
function stop(event){event.preventDefault();event.stopImmediatePropagation();}
