import{describe,expect,it}from'vitest';import{parseEnhancedSyntax}from'./enhancedSyntax.js';import{normalizeDesmosLatex,parseDesmosContour,parseDesmosFieldQuantity,parseDesmosGradient,parseDesmosParameter,parseDesmosSlopeField,parseDesmosTransform,parseDesmosVectorField}from'./desmosLatex.js';
describe('enhanced Desmos syntax',()=>{
  it('parses vectors and vector fields',()=>{expect(parseEnhancedSyntax('vec a = <<2,3>>')).toMatchObject({kind:'vector',name:'a',components:['2','3']});expect(parseEnhancedSyntax('vec F(x,y) = <<-y,x>>')).toMatchObject({kind:'vector-field',variables:['x','y']});expect(parseEnhancedSyntax('vec F = <<-y,x')).toMatchObject({kind:'vector',components:['-y','x']});});
  it('parses calculus notation',()=>{expect(parseEnhancedSyntax('partial x y f(x,y)')).toMatchObject({kind:'partial',variables:['x','y']});expect(parseEnhancedSyntax('d n x f(x)')).toMatchObject({kind:'derivative',order:'n'});expect(parseEnhancedSyntax('grad f(x,y)')).toMatchObject({kind:'grad'});expect(parseEnhancedSyntax("y'=x-y")).toMatchObject({kind:'slope-field'});});
  it('reads native and enhanced Desmos functions as fields',()=>{expect(parseDesmosVectorField('F\\left(x,y\\right)=\\left(-y,x\\right)')).toMatchObject({name:'F',x:'-y',y:'x'});expect(parseDesmosVectorField('F\\left(x,y\\right)=\\left\\langle-y,x\\right\\rangle')).toMatchObject({name:'F',x:'-y',y:'x'});expect(parseDesmosVectorField('\\vec{F}=<<-y,x>>')).toMatchObject({name:'F',x:'-y',y:'x'});expect(parseDesmosVectorField('\\overrightarrow{F}=\\left\\langle x,-y\\right\\rangle')).toMatchObject({name:'F',x:'x',y:'-y'});expect(parseDesmosVectorField('\\overrightarrow{AB}=\\left\\langle xy,x\\sin(y)\\right\\rangle')).toMatchObject({name:'AB',x:'x*y',y:'x*sin(y)'});expect(parseDesmosVectorField('\\vec{F}=<<-y,x')).toMatchObject({name:'F',x:'-y',y:'x'});expect(parseDesmosVectorField('f(x)=x')).toBeNull();});
  it('treats prime and Leibniz slope notation as the same field',()=>{expect(parseDesmosSlopeField("y^{\\prime}=x-y")).toMatchObject({kind:'slope-field',x:'1',y:'x-y'});expect(parseDesmosSlopeField("y^\\prime=y-x")).toMatchObject({kind:'slope-field',y:'y-x'});expect(parseDesmosSlopeField('\\frac{dy}{dx}=x-y')).toMatchObject({kind:'slope-field',y:'x-y'});expect(parseDesmosSlopeField('y=x')).toBeNull();});
  it('treats plain dy/dx and y prime shorthand alike',()=>{expect(parseEnhancedSyntax('dy/dx=x-y')).toMatchObject({kind:'slope-field',expression:'x-y'});expect(parseEnhancedSyntax("y'=x-y")).toMatchObject({kind:'slope-field',expression:'x-y'});});
  it('reads scalar contour commands',()=>{expect(parseDesmosContour('\\operatorname{contour} f=x^2+y^2')).toMatchObject({kind:'contour',name:'f',expression:'x^2+y^2'});expect(parseDesmosContour('contour\\sin(x)\\cos(y)')).toMatchObject({expression:'sin(x)*cos(y)'});});
  it('reads scalar gradients as vector fields',()=>{expect(parseDesmosGradient('\\nabla f=x^2+y^2')).toMatchObject({kind:'gradient',name:'f',expression:'x^2+y^2'});expect(parseDesmosGradient('grad\\sin(x)\\cos(y)')).toMatchObject({expression:'sin(x)*cos(y)'});});
  it('reads divergence, curl and magnitude requests',()=>{expect(parseDesmosFieldQuantity('\\nabla\\cdot F')).toMatchObject({quantity:'div',fieldName:'F'});expect(parseDesmosFieldQuantity('\\nabla\\times F')).toMatchObject({quantity:'curl'});expect(parseDesmosFieldQuantity('magnitude(F)')).toMatchObject({quantity:'magnitude'});});
  it('reads nonlinear coordinate transforms',()=>expect(parseDesmosTransform('\\operatorname{transform}T(x,y)=<<x+y,x-y>>')).toMatchObject({name:'T',x:'x+y',y:'x-y'}));
  it('normalizes common Desmos latex',()=>expect(normalizeDesmosLatex('\\frac{x}{2}+\\sin\\left(y\\right)')).toBe('((x)/(2))+sin(y)'));
  it('normalizes implicit Desmos products and grouped roots',()=>{expect(normalizeDesmosLatex('xy+x\\sin\\left(y\\right)')).toBe('x*y+x*sin(y)');expect(normalizeDesmosLatex('\\sqrt{x}y')).toBe('sqrt(x)y');});
  it('reads Desmos scalar parameters',()=>{expect(parseDesmosParameter('a=2')).toEqual({name:'a',expression:'2'});expect(parseDesmosParameter('x=2')).toBeNull();});
});
