import{differentiateExpression,toLatex}from'./symbolic.js';

export function parseMatrix(source){
  const text=String(source||'').replace(/\\left|\\right/g,'').trim();if(text[0]!=='['||text.at(-1)!==']')throw new Error('Use a matrix such as [[1,2],[3,4]].');
  const rows=splitTopLevel(text.slice(1,-1),',').map(row=>{const value=row.trim();if(value[0]!=='['||value.at(-1)!==']')throw new Error('Every matrix row must use [ ].');return splitTopLevel(value.slice(1,-1),',').map(cell=>cell.trim());});
  if(!rows.length||!rows[0].length||rows.some(row=>row.length!==rows[0].length||row.some(cell=>!cell)))throw new Error('Matrix rows must be nonempty and the same length.');return rows;
}
export function matrixLatex(rows){return`\\left[${rows.map(row=>`\\left[${row.map(value=>typeof value==='number'?clean(value):value).join(',')}\\right]`).join(',')}\\right]`;}
export function resizeMatrix(source,rowDelta=0,columnDelta=0){const rows=parseMatrix(source).map(row=>[...row]),targetRows=Math.max(1,rows.length+rowDelta),targetColumns=Math.max(1,rows[0].length+columnDelta);while(rows.length<targetRows)rows.push(Array(rows[0].length).fill('0'));rows.length=targetRows;for(const row of rows){while(row.length<targetColumns)row.push('0');row.length=targetColumns;}return matrixLatex(rows);}
export function transposeMatrix(matrix){return matrix[0].map((_,column)=>matrix.map(row=>row[column]));}
export function addMatrices(a,b,sign=1){sameShape(a,b);return a.map((row,i)=>row.map((value,j)=>number(value)+sign*number(b[i][j])));}
export function multiplyMatrices(a,b){if(a[0].length!==b.length)throw new Error(`Cannot multiply ${a.length}×${a[0].length} by ${b.length}×${b[0].length}.`);return a.map(row=>b[0].map((_,j)=>row.reduce((sum,value,k)=>sum+number(value)*number(b[k][j]),0)));}
export function determinant(matrix){const a=numericSquare(matrix),n=a.length;let result=1;for(let column=0;column<n;column++){let pivot=column;for(let row=column+1;row<n;row++)if(Math.abs(a[row][column])>Math.abs(a[pivot][column]))pivot=row;if(Math.abs(a[pivot][column])<1e-12)return 0;if(pivot!==column){[a[pivot],a[column]]=[a[column],a[pivot]];result*=-1;}const value=a[column][column];result*=value;for(let row=column+1;row<n;row++){const factor=a[row][column]/value;for(let j=column+1;j<n;j++)a[row][j]-=factor*a[column][j];}}return clean(result);}
export function inverseMatrix(matrix){const left=numericSquare(matrix),n=left.length,right=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0));for(let column=0;column<n;column++){let pivot=column;for(let row=column+1;row<n;row++)if(Math.abs(left[row][column])>Math.abs(left[pivot][column]))pivot=row;if(Math.abs(left[pivot][column])<1e-12)throw new Error('This matrix is singular, so it has no inverse.');[left[pivot],left[column]]=[left[column],left[pivot]];[right[pivot],right[column]]=[right[column],right[pivot]];const scale=left[column][column];for(let j=0;j<n;j++){left[column][j]/=scale;right[column][j]/=scale;}for(let row=0;row<n;row++)if(row!==column){const factor=left[row][column];for(let j=0;j<n;j++){left[row][j]-=factor*left[column][j];right[row][j]-=factor*right[column][j];}}}return right.map(row=>row.map(clean));}
export function matrixRank(matrix){const a=matrix.map(row=>row.map(number));let rank=0;for(let column=0;column<a[0].length&&rank<a.length;column++){let pivot=rank;for(let row=rank+1;row<a.length;row++)if(Math.abs(a[row][column])>Math.abs(a[pivot][column]))pivot=row;if(Math.abs(a[pivot][column])<1e-12)continue;[a[pivot],a[rank]]=[a[rank],a[pivot]];for(let row=rank+1;row<a.length;row++){const factor=a[row][column]/a[rank][column];for(let j=column;j<a[0].length;j++)a[row][j]-=factor*a[rank][j];}rank++;}return rank;}
export function solveLinearSystem(matrix,vector){const column=vector.length&&Array.isArray(vector[0])?vector:vector.map(value=>[value]);if(column.length!==matrix.length||column.some(row=>row.length!==1))throw new Error('The answer vector must have one value per matrix row.');return multiplyMatrices(inverseMatrix(matrix),column);}
export function jacobianMatrix(expressions,variables){if(!expressions.length||!variables.length)throw new Error('Jacobian needs functions and variables.');return expressions.map(expression=>variables.map(variable=>toLatex(differentiateExpression(expression,variable))));}
export function hessianMatrix(expression,variables){if(!expression||!variables.length)throw new Error('Hessian needs a function and variables.');return variables.map(a=>variables.map(b=>toLatex(differentiateExpression(differentiateExpression(expression,a),b))));}
export function runMatrixCommand(command,args){const name=command.toLowerCase();if(name==='transpose'||name==='trans')return matrixLatex(transposeMatrix(parseMatrix(args[0])));if(name==='det')return String(determinant(parseMatrix(args[0])));if(name==='inverse'||name==='inv')return matrixLatex(inverseMatrix(parseMatrix(args[0])));if(name==='rank')return String(matrixRank(parseMatrix(args[0])));if(name==='matadd'||name==='matsub')return matrixLatex(addMatrices(parseMatrix(args[0]),parseMatrix(args[1]),name==='matsub'?-1:1));if(name==='matmul')return matrixLatex(multiplyMatrices(parseMatrix(args[0]),parseMatrix(args[1])));if(name==='linsolve')return matrixLatex(solveLinearSystem(parseMatrix(args[0]),parseMatrix(args[1])));if(name==='jacobian'||name==='jac')return matrixLatex(jacobianMatrix(parseList(args[0]),parseList(args[1])));if(name==='hessian'||name==='hess')return matrixLatex(hessianMatrix(args[0],parseList(args[1])));return null;}

function parseList(source){const text=String(source||'').trim();if(text[0]!=='['||text.at(-1)!==']')throw new Error('Use a list such as [x,y].');return splitTopLevel(text.slice(1,-1),',').map(value=>value.trim()).filter(Boolean);}
function splitTopLevel(value,separator){const out=[];let depth=0,start=0;for(let i=0;i<value.length;i++){const c=value[i];if('([{'.includes(c))depth++;else if(')]}'.includes(c))depth--;else if(c===separator&&depth===0){out.push(value.slice(start,i));start=i+1;}}out.push(value.slice(start));return out;}
function number(value){const result=Number(value);if(!Number.isFinite(result))throw new Error('This operation currently needs numeric matrix entries.');return result;}
function numericSquare(matrix){if(matrix.length!==matrix[0].length)throw new Error('This operation needs a square matrix.');return matrix.map(row=>row.map(number));}
function sameShape(a,b){if(a.length!==b.length||a[0].length!==b[0].length)throw new Error('Matrices must have the same dimensions.');}
function clean(value){return Math.abs(value)<1e-12?0:Number(value.toPrecision(12));}
