import{parseExpression}from'../../../src/lib/math/expression.js';

const num=value=>({type:'number',value:Number(value)}),name=value=>({type:'name',name:value}),binary=(op,left,right)=>({type:'binary',op,left,right}),call=(fn,...args)=>({type:'call',name:fn,args});

export function simplifyExpression(source){return toSource(simplify(parseExpression(source)));}

export function differentiateExpression(source,variable='x',order=1){let ast=parseExpression(source);const count=Math.max(0,Math.min(12,Number(order)||1));for(let i=0;i<count;i++)ast=simplify(derivative(ast,variable));return toSource(ast);}

export function integrateExpression(source,variable='x'){return toSource(simplify(integral(parseExpression(source),variable)));}

export function solvePolynomial(equation,variable='x'){
  const parts=splitEquation(equation),ast=parts.length===2?binary('-',parseExpression(parts[0]),parseExpression(parts[1])):parseExpression(parts[0]),coefficients=polynomial(ast,variable);
  if(!coefficients||coefficients.length>3)throw new Error('Symbolic solve currently supports linear and quadratic polynomial equations.');
  const[a=0,b=0,c=0]=coefficients.map(constantValue);if([a,b,c].some(value=>value===null))throw new Error('Polynomial coefficients must be numeric constants.');
  const epsilon=1e-12;if(Math.abs(c)>epsilon){const discriminant=b*b-4*c*a;if(discriminant<0)return[];if(Math.abs(discriminant)<epsilon)return[cleanNumber(-b/(2*c))];const root=Math.sqrt(discriminant);return[cleanNumber((-b-root)/(2*c)),cleanNumber((-b+root)/(2*c))];}if(Math.abs(b)>epsilon)return[cleanNumber(-a/b)];return Math.abs(a)<epsilon?'all':[];
}

export function toLatex(source){return toLatexAst(typeof source==='string'?parseExpression(source):source);}

function derivative(node,variable){
  if(node.type==='number')return num(0);if(node.type==='name')return num(node.name===variable?1:0);if(node.type==='unary')return node.op==='-'?{type:'unary',op:'-',value:derivative(node.value,variable)}:derivative(node.value,variable);
  if(node.type==='binary'){const u=node.left,v=node.right,du=derivative(u,variable),dv=derivative(v,variable);if(node.op==='+'||node.op==='-')return binary(node.op,du,dv);if(node.op==='*')return binary('+',binary('*',du,v),binary('*',u,dv));if(node.op==='/')return binary('/',binary('-',binary('*',du,v),binary('*',u,dv)),binary('^',v,num(2)));if(node.op==='^'){if(v.type==='number')return binary('*',binary('*',v,binary('^',u,num(v.value-1))),du);return binary('*',binary('^',u,v),binary('+',binary('*',dv,call('ln',u)),binary('*',v,binary('/',du,u))));}}
  if(node.type==='call'){const u=node.args[0],du=derivative(u,variable),fn=node.name.toLowerCase(),outer={sin:call('cos',u),cos:{type:'unary',op:'-',value:call('sin',u)},tan:binary('^',call('sec',u),num(2)),exp:call('exp',u),ln:binary('/',num(1),u),log:binary('/',num(1),u),sqrt:binary('/',num(1),binary('*',num(2),call('sqrt',u))),asin:binary('/',num(1),call('sqrt',binary('-',num(1),binary('^',u,num(2))))),arcsin:binary('/',num(1),call('sqrt',binary('-',num(1),binary('^',u,num(2))))),acos:{type:'unary',op:'-',value:binary('/',num(1),call('sqrt',binary('-',num(1),binary('^',u,num(2)))))},arccos:{type:'unary',op:'-',value:binary('/',num(1),call('sqrt',binary('-',num(1),binary('^',u,num(2)))))},atan:binary('/',num(1),binary('+',num(1),binary('^',u,num(2)))),arctan:binary('/',num(1),binary('+',num(1),binary('^',u,num(2)))),sinh:call('cosh',u),cosh:call('sinh',u),tanh:binary('^',call('sech',u),num(2))}[fn];if(!outer)throw new Error(`No symbolic derivative rule for ${node.name}.`);return binary('*',outer,du);}
  throw new Error('Unsupported symbolic expression.');
}

function integral(node,variable){
  if(!depends(node,variable))return binary('*',node,name(variable));if(node.type==='name'&&node.name===variable)return binary('/',binary('^',name(variable),num(2)),num(2));if(node.type==='unary'&&node.op==='-')return{type:'unary',op:'-',value:integral(node.value,variable)};
  if(node.type==='binary'){if(node.op==='+'||node.op==='-')return binary(node.op,integral(node.left,variable),integral(node.right,variable));if(node.op==='*'){if(!depends(node.left,variable))return binary('*',node.left,integral(node.right,variable));if(!depends(node.right,variable))return binary('*',node.right,integral(node.left,variable));}if(node.op==='^'&&node.left.type==='name'&&node.left.name===variable&&node.right.type==='number'){if(node.right.value===-1)return call('ln',call('abs',name(variable)));return binary('/',binary('^',name(variable),num(node.right.value+1)),num(node.right.value+1));}}
  if(node.type==='call'&&node.args[0]?.type==='name'&&node.args[0].name===variable){const fn=node.name.toLowerCase();if(fn==='sin')return{type:'unary',op:'-',value:call('cos',name(variable))};if(fn==='cos')return call('sin',name(variable));if(fn==='exp')return call('exp',name(variable));if(fn==='sec'&&node.args.length===1)return call('ln',binary('+',call('sec',name(variable)),call('tan',name(variable))));}
  throw new Error('No elementary antiderivative rule is available for this expression.');
}

function simplify(node){
  if(node.type==='number'||node.type==='name')return node;if(node.type==='unary'){const value=simplify(node.value);if(value.type==='number')return num(node.op==='-'?-value.value:value.value);if(node.op==='-'&&value.type==='unary'&&value.op==='-')return value.value;return{...node,value};}
  if(node.type==='call')return{...node,args:node.args.map(simplify)};const left=simplify(node.left),right=simplify(node.right);if(left.type==='number'&&right.type==='number'){const a=left.value,b=right.value;return num(node.op==='+'?a+b:node.op==='-'?a-b:node.op==='*'?a*b:node.op==='/'?a/b:a**b);}if(node.op==='+'&&isZero(left))return right;if(node.op==='+'&&isZero(right)||node.op==='-'&&isZero(right))return left;if(node.op==='-'&&same(left,right))return num(0);if(node.op==='*'&&(isZero(left)||isZero(right)))return num(0);if(node.op==='*'&&isOne(left))return right;if(node.op==='*'&&isOne(right))return left;if(node.op==='/'&&isZero(left))return num(0);if(node.op==='/'&&isOne(right))return left;if(node.op==='^'&&isZero(right))return num(1);if(node.op==='^'&&isOne(right))return left;return binary(node.op,left,right);
}

function polynomial(node,variable){if(node.type==='number')return[node];if(node.type==='name')return node.name===variable?[num(0),num(1)]:[node];if(node.type==='unary'&&node.op==='-')return polynomial(node.value,variable)?.map(value=>simplify({type:'unary',op:'-',value}));if(node.type!=='binary')return null;const left=polynomial(node.left,variable),right=polynomial(node.right,variable);if(node.op==='+'||node.op==='-'){if(!left||!right)return null;return trim(Array.from({length:Math.max(left.length,right.length)},(_,i)=>simplify(binary(node.op,left[i]||num(0),right[i]||num(0)))));}if(node.op==='*'){if(!left||!right)return null;const out=Array(left.length+right.length-1).fill(null).map(()=>num(0));for(let i=0;i<left.length;i++)for(let j=0;j<right.length;j++)out[i+j]=simplify(binary('+',out[i+j],binary('*',left[i],right[j])));return trim(out);}if(node.op==='/'&&!depends(node.right,variable)&&left)return trim(left.map(value=>simplify(binary('/',value,node.right))));if(node.op==='^'&&node.right.type==='number'&&Number.isInteger(node.right.value)&&node.right.value>=0&&node.right.value<=2){let out=[num(1)];for(let i=0;i<node.right.value;i++)out=polynomial(binary('*',fromPolynomial(out,variable),node.left),variable);return out;}return null;}

function fromPolynomial(values,variable){return values.reduce((sum,value,index)=>binary('+',sum,index?binary('*',value,binary('^',name(variable),num(index))):value),num(0));}
function trim(values){while(values.length>1&&isZero(values.at(-1)))values.pop();return values;}
function constantValue(node){const value=simplify(node);return value.type==='number'&&Number.isFinite(value.value)?value.value:null;}
function depends(node,variable){if(node.type==='name')return node.name===variable;if(node.value)return depends(node.value,variable);if(node.left&&depends(node.left,variable)||node.right&&depends(node.right,variable))return true;return node.args?.some(value=>depends(value,variable))||false;}
function same(a,b){return toSource(a)===toSource(b);}function isZero(node){return node.type==='number'&&node.value===0;}function isOne(node){return node.type==='number'&&node.value===1;}
function splitEquation(value){let depth=0;for(let i=0;i<value.length;i++){if(value[i]==='(')depth++;else if(value[i]===')')depth--;else if(value[i]==='='&&depth===0)return[value.slice(0,i),value.slice(i+1)];}return[value];}
function cleanNumber(value){return Math.abs(value)<1e-12?0:Number(value.toPrecision(12));}
function toSource(node){if(node.type==='number')return cleanNumber(node.value).toString();if(node.type==='name')return node.name;if(node.type==='unary'){const value=toSource(node.value);return node.value.type==='name'||node.value.type==='number'||node.value.type==='call'?`${node.op}${value}`:`${node.op}(${value})`;}if(node.type==='call')return`${node.name}(${node.args.map(toSource).join(',')})`;return`(${toSource(node.left)}${node.op}${toSource(node.right)})`;}
function toLatexAst(node){if(node.type==='number')return cleanNumber(node.value).toString();if(node.type==='name')return node.name;if(node.type==='unary')return `${node.op}${toLatexAst(node.value)}`;if(node.type==='call'){const fn={sin:'\\sin',cos:'\\cos',tan:'\\tan',sec:'\\sec',ln:'\\ln',log:'\\log',sqrt:'\\sqrt',exp:'\\exp',abs:'\\left|' }[node.name]||`\\operatorname{${node.name}}`;if(node.name==='sqrt')return`\\sqrt{${toLatexAst(node.args[0])}}`;if(node.name==='abs')return`\\left|${toLatexAst(node.args[0])}\\right|`;return`${fn}\\left(${node.args.map(toLatexAst).join(',')}\\right)`;}const left=toLatexAst(node.left),right=toLatexAst(node.right);if(node.op==='/')return`\\frac{${left}}{${right}}`;if(node.op==='^')return`{${left}}^{${right}}`;return`\\left(${left}${node.op==='*'?'\\cdot ':node.op}${right}\\right)`;}
