import {paletteColor} from '../colorPalettes.js';
import {sampleField,finiteRange} from './fieldSampler.js';
import {extractContourPaths,smoothContourPath} from './smoothContours.js';

export function buildFieldSVG({field,bounds,width,height,options={},trajectories=[]}){
  const x=p=>(p-bounds.minX)/(bounds.maxX-bounds.minX)*width,y=p=>(p-bounds.minY)/(bounds.maxY-bounds.minY)*height,esc=s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;');
  const out=[`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">`,`<rect width="100%" height="100%" fill="${esc(options.background||'#071526')}"/>`,`<defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0L10 5L0 10Z" fill="context-stroke"/></marker></defs>`];
  if(options.grid){const step=niceStep((bounds.maxX-bounds.minX)/10);for(let gx=Math.ceil(bounds.minX/step)*step;gx<=bounds.maxX;gx+=step)out.push(`<path d="M${x(gx)} 0V${height}" stroke="#537895" stroke-opacity=".25"/>`);for(let gy=Math.ceil(bounds.minY/step)*step;gy<=bounds.maxY;gy+=step)out.push(`<path d="M0 ${y(gy)}H${width}" stroke="#537895" stroke-opacity=".25"/>`);}
  if(options.axes){if(bounds.minX<=0&&bounds.maxX>=0)out.push(`<path d="M${x(0)} 0V${height}" stroke="#dcecff" stroke-opacity=".65"/>`);if(bounds.minY<=0&&bounds.maxY>=0)out.push(`<path d="M0 ${y(0)}H${width}" stroke="#dcecff" stroke-opacity=".65"/>`);}
  if(options.contours){const grid=sampleField(field,bounds,Math.min(180,options.sampleCols||128),Math.round(Math.min(180,options.sampleCols||128)*height/width)),values=grid.get(options.contourQuantity||'magnitude');let[lo,hi]=finiteRange(values,.01,.99);const count=Math.max(3,Math.min(24,options.contourLevels||9));for(let i=1;i<=count;i++){const level=lo+i/(count+1)*(hi-lo),paths=extractContourPaths(values,grid.cols,grid.rows,level,width,height);for(const raw of paths){const path=smoothContourPath(raw,options.contourSmoothing||0),d=path.map((p,k)=>`${k?'L':'M'}${p[0].toFixed(2)} ${p[1].toFixed(2)}`).join('');out.push(`<path d="${d}" fill="none" stroke="${paletteColor('gold',(level-lo)/(hi-lo),.85)}" stroke-width="1.2"/>`);}if(options.contourLabels&&i%5===0)out.push(`<text x="8" y="${16+i*12}" fill="#f7df93" font-family="monospace" font-size="10">${level.toPrecision(3)}</text>`);}}
  if(options.arrows){const n=Math.max(8,Math.min(42,options.arrowDensity||22)),nx=Math.max(8,Math.round(n*width/height)),len=Math.min(width/nx,height/n)*.58;for(let iy=0;iy<n;iy++)for(let ix=0;ix<nx;ix++){const px=bounds.minX+(ix+.5)/nx*(bounds.maxX-bounds.minX),py=bounds.minY+(iy+.5)/n*(bounds.maxY-bounds.minY),v=field.evaluate(px,py),m=Math.hypot(...v);if(!Number.isFinite(m)||m<1e-10)continue;const a=Math.atan2(v[1],v[0]),x1=x(px),y1=y(py),x2=x1+Math.cos(a)*len,y2=y1+Math.sin(a)*len;out.push(`<path d="M${x1.toFixed(2)} ${y1.toFixed(2)}L${x2.toFixed(2)} ${y2.toFixed(2)}" stroke="${paletteColor(options.palette||'magnitude',Math.min(1,m),options.opacity??.85)}" stroke-width="1.4" marker-end="url(#arrow)"/>`);}}
  for(const line of trajectories){const d=line.points.map((p,k)=>`${k?'L':'M'}${x(p[0]).toFixed(2)} ${y(p[1]).toFixed(2)}`).join('');out.push(`<path d="${d}" fill="none" stroke="${line.color}" stroke-width="2"/>`);}
  out.push('</svg>');return out.join('');
}
function niceStep(raw){const p=10**Math.floor(Math.log10(raw)),n=raw/p;return(n<2?1:n<5?2:5)*p;}
