<template><canvas ref='canvas' class='field-overlay' aria-hidden='true'></canvas></template>
<script>
import bus from '../lib/bus.js';
import {findCriticalPoints} from '../lib/math/fieldAnalysis.js';
import {arrowSegment,createViewportTransform} from '../lib/math/overlayGeometry.js';
import {derivedScalar} from '../lib/math/fieldQuantities.js';
import {finiteRange,sampleField} from '../lib/math/fieldSampler.js';
import {extractContourPaths,smoothContourPath} from '../lib/math/smoothContours.js';
import {paletteColor} from '../lib/colorPalettes.js';
export default{
  props:['scene'],
  data:()=>({field:null,compareField:null,probePoint:null,trajectories:[],criticalPoints:null,options:{grid:true,axes:true,arrows:true,heatmap:false,contours:false,critical:true,arrowDensity:22,opacity:.82,palette:'magnitude',heatmapPalette:'viridis',matchParticles:false,contourQuantity:'magnitude',contourLevels:9,linkContourDensity:true,contourSmoothing:1,sampleQuality:'balanced',probe:true,trajectories:true,particlePalette:'cyan',particleColor:'#4ec4ff'},timer:0}),
  mounted(){this.ctx=this.$refs.canvas.getContext('2d',{alpha:true});this.redraw=this.redraw.bind(this);this.onField=m=>{this.field=m;this.trajectories=[];this.criticalPoints=null;this.schedule();};this.onCompare=m=>{this.compareField=m;this.schedule();};this.onOptions=o=>{Object.assign(this.options,o);this.schedule();};this.onBounds=()=>{this.criticalPoints=null;this.schedule();};this.onMove=e=>{if(!this.options.probe||isControl(e.target)){this.probePoint=null;return;}this.probePoint=this.eventPoint(e);this.schedule(16);};this.onClick=e=>{if(!this.options.trajectories||isControl(e.target))return;const p=this.eventPoint(e);if(!p||!this.field)return;this.trajectories.push({points:traceBoth(this.field,p,this.scene.getBoundingBox()),color:paletteColor(this.options.palette,.72,1)});if(this.trajectories.length>16)this.trajectories.shift();this.schedule(0);};this.onClear=()=>{this.trajectories=[];this.schedule(0);};bus.on('studio-field-model',this.onField);bus.on('studio-compare-model',this.onCompare);bus.on('studio-overlay-options',this.onOptions);bus.on('studio-clear-trajectories',this.onClear);bus.on('bbox-change',this.onBounds);window.addEventListener('resize',this.onBounds);window.addEventListener('pointermove',this.onMove,{passive:true});window.addEventListener('click',this.onClick);this.schedule();},
  beforeUnmount(){bus.off('studio-field-model',this.onField);bus.off('studio-compare-model',this.onCompare);bus.off('studio-overlay-options',this.onOptions);bus.off('studio-clear-trajectories',this.onClear);bus.off('bbox-change',this.onBounds);window.removeEventListener('resize',this.onBounds);window.removeEventListener('pointermove',this.onMove);window.removeEventListener('click',this.onClick);clearTimeout(this.timer);},
  methods:{
    schedule(delay=60){clearTimeout(this.timer);this.timer=setTimeout(this.redraw,delay);},
    eventPoint(e){const rect=this.scene?.getCanvasRect(),b=this.scene?.getBoundingBox();if(!rect||!b||e.clientX<rect.left||e.clientX>rect.left+rect.width||e.clientY<rect.top||e.clientY>rect.top+rect.height)return null;return{x:b.minX+(e.clientX-rect.left)/rect.width*(b.maxX-b.minX),y:b.minY+(e.clientY-rect.top)/rect.height*(b.maxY-b.minY)};},
    redraw(){const canvas=this.$refs.canvas,dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';}const ctx=this.ctx;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!this.scene)return;const b=this.scene.getBoundingBox(),rect=this.scene.getCanvasRect();if(!b||!rect.width||!rect.height)return;const map=createViewportTransform(b,rect).point;let sampled=null;if(this.field&&(this.options.heatmap||this.options.contours)){const cols={eco:72,balanced:128,detail:220}[this.options.sampleQuality]||128,rows=Math.max(40,Math.round(cols*rect.height/rect.width));sampled=sampleField(this.field,b,cols,rows);}if(this.options.heatmap&&sampled)this.drawHeatmap(sampled,rect);if(this.options.grid)this.drawGrid(w,h,b,map);if(this.options.axes)this.drawAxes(w,h,map);if(this.options.contours&&sampled)this.drawContours(sampled,rect);if(this.options.arrows&&this.field)this.drawArrows(b,rect,this.field);if(this.options.arrows&&this.compareField)this.drawArrows(b,rect,this.compareField,'rgba(255,111,183,.75)');this.drawTrajectories(map);if(this.options.critical&&this.field)this.drawCritical(b,map);if(this.options.probe&&this.probePoint&&this.field)this.drawProbe(b,map);},
    drawGrid(w,h,b,map){const ctx=this.ctx,step=niceStep((b.maxX-b.minX)/10);ctx.strokeStyle='rgba(116,166,207,.16)';ctx.lineWidth=1;ctx.beginPath();for(let x=Math.ceil(b.minX/step)*step;x<=b.maxX;x+=step){const[px]=map(x,0);ctx.moveTo(px,0);ctx.lineTo(px,h);}for(let y=Math.ceil(b.minY/step)*step;y<=b.maxY;y+=step){const[,py]=map(0,y);ctx.moveTo(0,py);ctx.lineTo(w,py);}ctx.stroke();},
    drawAxes(w,h,map){const ctx=this.ctx,[x0,y0]=map(0,0);ctx.strokeStyle='rgba(205,230,250,.52)';ctx.lineWidth=1.25;ctx.beginPath();if(x0>=0&&x0<=w){ctx.moveTo(x0,0);ctx.lineTo(x0,h);}if(y0>=0&&y0<=h){ctx.moveTo(0,y0);ctx.lineTo(w,y0);}ctx.stroke();},
    drawArrows(b,rect,field,fixedColor){const ctx=this.ctx,n=Math.max(8,Math.min(42,this.options.arrowDensity)),nx=Math.max(8,Math.round(n*rect.width/rect.height)),maxLen=Math.min(rect.width/nx,rect.height/n)*.72,samples=[];for(let iy=0;iy<n;iy++)for(let ix=0;ix<nx;ix++){const x=b.minX+(ix+.5)/nx*(b.maxX-b.minX),y=b.minY+(iy+.5)/n*(b.maxY-b.minY),v=field.evaluate(x,y),m=Math.hypot(...v);if(Number.isFinite(m))samples.push({x,y,v,m});}const sorted=samples.map(s=>s.m).sort((a,c)=>a-c),vmax=sorted[Math.floor((sorted.length-1)*.95)]||1,transform=createViewportTransform(b,rect),paletteName=this.options.matchParticles?this.options.particlePalette:this.options.palette;ctx.save();ctx.lineCap='round';for(const s of samples){if(s.m<1e-10)continue;const t=Math.min(1,Math.sqrt(s.m/vmax)),len=maxLen*(.32+.68*t),arrow=arrowSegment(transform,s.x,s.y,s.v[0],s.v[1],len);if(!arrow)continue;const color=fixedColor||arrowColor(paletteName,t,s.v,this.options.opacity,this.options.particleColor);drawArrow(ctx,arrow,len,'rgba(1,8,18,.8)',3.4);drawArrow(ctx,arrow,len,color,1.45);}ctx.restore();if(!fixedColor&&paletteName==='magnitude')this.drawLegend(rect,vmax,paletteName,'|F|');},
    drawHeatmap(grid,rect){const ctx=this.ctx,values=grid.magnitude,[lo,hi]=finiteRange(values),cw=rect.width/grid.cols,ch=rect.height/grid.rows;ctx.save();for(let j=0;j<grid.rows;j++)for(let i=0;i<grid.cols;i++){const k=j*(grid.cols+1)+i,t=normalize(values[k],lo,hi);ctx.fillStyle=paletteColor(this.options.heatmapPalette,t,.28);ctx.fillRect(rect.left+i*cw,rect.top+j*ch,cw+1,ch+1);}ctx.restore();this.drawLegend(rect,hi,this.options.heatmapPalette,'|F|');},
    drawContours(grid,rect){const ctx=this.ctx,q=this.options.contourQuantity,values=grid.get(q);let[lo,hi]=finiteRange(values,.01,.99);if(q==='divergence'||q==='curl'){const m=Math.max(Math.abs(lo),Math.abs(hi));lo=-m;hi=m;}if(!Number.isFinite(lo)||hi===lo)return;const requested=this.options.linkContourDensity?3+Math.round((this.options.arrowDensity-8)/34*21):this.options.contourLevels||9,count=Math.max(3,Math.min(24,requested)),levels=[];for(let i=1;i<=count;i++)levels.push(lo+i/(count+1)*(hi-lo));if((q==='divergence'||q==='curl')&&lo<0&&hi>0)levels.push(0);levels.sort((a,b)=>a-b);ctx.save();ctx.translate(rect.left,rect.top);ctx.lineJoin='round';ctx.lineCap='round';levels.forEach((level,index)=>{const paths=extractContourPaths(values,grid.cols,grid.rows,level,rect.width,rect.height),major=Math.abs(level)<1e-12||index%5===0;for(const path of paths){const p=smoothContourPath(path,this.options.contourSmoothing||0);strokePath(ctx,p,'rgba(2,8,18,.88)',major?4.2:3);strokePath(ctx,p,paletteColor(q==='divergence'||q==='curl'?'vik':'gold',normalize(level,lo,hi),major ? .95 : .66),major?1.8:1.05);}});ctx.restore();},
    drawTrajectories(map){const ctx=this.ctx;ctx.save();ctx.lineJoin='round';ctx.lineCap='round';for(const line of this.trajectories){const points=line.points.map(p=>map(p[0],p[1]));strokePath(ctx,points,'rgba(1,8,18,.9)',4.5);strokePath(ctx,points,line.color,2);}ctx.restore();},
    drawProbe(b,map){const p=this.probePoint,v=this.field.evaluate(p.x,p.y),m=Math.hypot(...v),div=derivedScalar(this.field,'divergence',b)(p.x,p.y),curl=derivedScalar(this.field,'curl',b)(p.x,p.y),[x,y]=map(p.x,p.y),ctx=this.ctx,lines=[`(${fmt(p.x)}, ${fmt(p.y)})`,`F = (${fmt(v[0])}, ${fmt(v[1])})`,`|F| ${fmt(m)}   div ${fmt(div)}   curl ${fmt(curl)}`];ctx.save();ctx.fillStyle='#fff';ctx.strokeStyle='#07111f';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.stroke();ctx.fill();const boxX=Math.min(innerWidth-270,x+12),boxY=Math.max(8,y-64);ctx.fillStyle='rgba(2,8,18,.92)';ctx.strokeStyle='#365875';ctx.lineWidth=1;ctx.fillRect(boxX,boxY,255,55);ctx.strokeRect(boxX,boxY,255,55);ctx.font='11px ui-monospace,monospace';lines.forEach((line,i)=>{ctx.fillStyle=i?'#9ec8ed':'#fff';ctx.fillText(line,boxX+8,boxY+15+i*16);});ctx.restore();},
    drawLegend(rect,max,name,label){const ctx=this.ctx,x=rect.left+14,y=rect.top+14,w=132,h=8,g=ctx.createLinearGradient(x,0,x+w,0);for(let i=0;i<=8;i++)g.addColorStop(i/8,paletteColor(name,i/8,1));ctx.save();ctx.fillStyle='rgba(2,8,18,.82)';ctx.fillRect(x-7,y-7,w+14,34);ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.fillStyle='#dcecff';ctx.font='10px system-ui';ctx.fillText(`${label} low`,x,y+21);ctx.textAlign='right';ctx.fillText(`high ${fmt(max)}`,x+w,y+21);ctx.restore();},
    drawCritical(b,map){const ctx=this.ctx;if(!this.criticalPoints)this.criticalPoints=findCriticalPoints(this.field.evaluate,b,{grid:22});this.criticalPoints.forEach(p=>{const[x,y]=map(p.x,p.y);ctx.fillStyle=p.classification==='saddle'?'#ffb454':'#ff5d8f';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#dfefff';ctx.font='11px system-ui';ctx.fillText(p.classification,x+8,y-7);});}
  }
};
function traceBoth(field,p,b){const backward=trace(field,p,b,-1).reverse(),forward=trace(field,p,b,1);return backward.slice(0,-1).concat(forward);}
function trace(field,p,b,direction){const out=[[p.x,p.y]],span=Math.min(b.maxX-b.minX,b.maxY-b.minY),step=span/420;let x=p.x,y=p.y;for(let i=0;i<900;i++){const advance=(px,py)=>{const v=field.evaluate(px,py),m=Math.hypot(...v);return!Number.isFinite(m)||m<1e-10?null:[v[0]/m*direction,v[1]/m*direction];},k1=advance(x,y);if(!k1)break;const k2=advance(x+k1[0]*step*.5,y+k1[1]*step*.5);if(!k2)break;const k3=advance(x+k2[0]*step*.5,y+k2[1]*step*.5);if(!k3)break;const k4=advance(x+k3[0]*step,y+k3[1]*step);if(!k4)break;x+=step*(k1[0]+2*k2[0]+2*k3[0]+k4[0])/6;y+=step*(k1[1]+2*k2[1]+2*k3[1]+k4[1])/6;if(x<b.minX||x>b.maxX||y<b.minY||y>b.maxY)break;out.push([x,y]);if(i>40&&Math.hypot(x-p.x,y-p.y)<step*.75)break;}return out;}
function strokePath(ctx,p,color,width){if(p.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(p[0][0],p[0][1]);for(let i=1;i<p.length;i++)ctx.lineTo(p[i][0],p[i][1]);ctx.stroke();}
function arrowColor(name,t,v,a,custom){if(name==='rainbow'){const h=(Math.atan2(v[1],v[0])+Math.PI)/(Math.PI*2);return`hsla(${Math.round(h*360)},85%,66%,${a})`;}if(name==='custom')return hexRgba(custom,a);return paletteColor(name,t,a);}
function drawArrow(ctx,a,len,color,width){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x1,a.y1);ctx.lineTo(a.x2,a.y2);ctx.stroke();const head=Math.min(6.5,len*.32);ctx.beginPath();ctx.moveTo(a.x2,a.y2);ctx.lineTo(a.x2-head*Math.cos(a.angle-.55),a.y2-head*Math.sin(a.angle-.55));ctx.lineTo(a.x2-head*Math.cos(a.angle+.55),a.y2-head*Math.sin(a.angle+.55));ctx.closePath();ctx.fill();}
function niceStep(raw){const p=10**Math.floor(Math.log10(raw)),n=raw/p;return(n<2?1:n<5?2:5)*p;}
function normalize(v,a,b){return Math.max(0,Math.min(1,(v-a)/(b-a||1)));}
function fmt(v){if(!Number.isFinite(v))return'—';const a=Math.abs(v);return a>=1000||a>0&&a<.001?v.toExponential(2):v.toFixed(a<10?3:1);}
function hexRgba(hex,a){const text=String(hex||'#4ec4ff').replace('#','');return`rgba(${parseInt(text.slice(0,2),16)},${parseInt(text.slice(2,4),16)},${parseInt(text.slice(4,6),16)},${a})`;}
function isControl(target){return target instanceof Element&&!!target.closest('.controls-container,.share');}
</script>
<style>.field-overlay{position:fixed;inset:0;z-index:2;pointer-events:none}</style>
