<template><canvas ref='canvas' class='field-overlay' aria-hidden='true'></canvas></template>
<script>
import bus from '../lib/bus.js';
import { findCriticalPoints } from '../lib/math/fieldAnalysis.js';
import { arrowSegment, contourSegments, createViewportTransform } from '../lib/math/overlayGeometry.js';
export default {
  props:['scene'],
  data:()=>({field:null,compareField:null,options:{grid:true,axes:true,arrows:true,heatmap:false,contours:false,critical:true,arrowDensity:22,opacity:.82,palette:'magnitude'},timer:0}),
  mounted(){
    this.ctx=this.$refs.canvas.getContext('2d'); this.redraw=this.redraw.bind(this); this.onField=m=>{this.field=m;this.schedule();};this.onCompare=m=>{this.compareField=m;this.schedule();}; this.onOptions=o=>{Object.assign(this.options,o);this.schedule();};
    bus.on('studio-field-model',this.onField);bus.on('studio-compare-model',this.onCompare);bus.on('studio-overlay-options',this.onOptions);bus.on('bbox-change',this.schedule,this);window.addEventListener('resize',this.schedule);this.schedule();
  },
  beforeUnmount(){bus.off('studio-field-model',this.onField);bus.off('studio-compare-model',this.onCompare);bus.off('studio-overlay-options',this.onOptions);bus.off('bbox-change',this.schedule,this);window.removeEventListener('resize',this.schedule);clearTimeout(this.timer);},
  methods:{
    schedule(){clearTimeout(this.timer);this.timer=setTimeout(this.redraw,60);},
    redraw(){
      const canvas=this.$refs.canvas,dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';}this.ctx.setTransform(dpr,0,0,dpr,0,0);this.ctx.clearRect(0,0,w,h);
      const b=this.scene.getBoundingBox();if(!b)return;const transform=createViewportTransform(b,this.scene.getCanvasRect());const map=transform.point;
      if(this.options.heatmap&&this.field)this.drawHeatmap(w,h,b);if(this.options.grid)this.drawGrid(w,h,b,map);if(this.options.axes)this.drawAxes(w,h,b,map);if(this.options.contours&&this.field?.scalar)this.drawContours(w,h,b);if(this.options.arrows&&this.field)this.drawArrows(w,h,b,map,this.field);if(this.options.arrows&&this.compareField)this.drawArrows(w,h,b,map,this.compareField,'rgba(255,111,183,.75)');if(this.options.critical&&this.field)this.drawCritical(b,map);
    },
    drawGrid(w,h,b,map){const ctx=this.ctx,step=niceStep((b.maxX-b.minX)/10);ctx.strokeStyle='rgba(116,166,207,.16)';ctx.lineWidth=1;ctx.beginPath();for(let x=Math.ceil(b.minX/step)*step;x<=b.maxX;x+=step){const [px]=map(x,0);ctx.moveTo(px,0);ctx.lineTo(px,h);}for(let y=Math.ceil(b.minY/step)*step;y<=b.maxY;y+=step){const [,py]=map(0,y);ctx.moveTo(0,py);ctx.lineTo(w,py);}ctx.stroke();},
    drawAxes(w,h,b,map){const ctx=this.ctx,[x0,y0]=map(0,0);ctx.strokeStyle='rgba(205,230,250,.52)';ctx.lineWidth=1.25;ctx.beginPath();if(x0>=0&&x0<=w){ctx.moveTo(x0,0);ctx.lineTo(x0,h);}if(y0>=0&&y0<=h){ctx.moveTo(0,y0);ctx.lineTo(w,y0);}ctx.stroke();},
    drawArrows(w,h,b,map,field,fixedColor){const ctx=this.ctx,n=Math.max(8,Math.min(42,this.options.arrowDensity)),rect=this.scene.getCanvasRect(),aspect=rect.width/rect.height,nx=Math.max(8,Math.round(n*aspect)),maxLen=Math.min(rect.width/nx,rect.height/n)*.72,samples=[];for(let iy=0;iy<n;iy++)for(let ix=0;ix<nx;ix++){const x=b.minX+(ix+.5)/nx*(b.maxX-b.minX),y=b.minY+(iy+.5)/n*(b.maxY-b.minY),v=field.evaluate(x,y),m=Math.hypot(...v);if(Number.isFinite(m))samples.push({x,y,v,m});}const sorted=samples.map(s=>s.m).sort((a,c)=>a-c),vmax=sorted[Math.floor((sorted.length-1)*.95)]||1,transform=createViewportTransform(b,rect);ctx.save();ctx.lineCap='round';samples.forEach(s=>{if(s.m<1e-10)return;const t=Math.min(1,Math.sqrt(s.m/vmax)),len=maxLen*(.32+.68*t),arrow=arrowSegment(transform,s.x,s.y,s.v[0],s.v[1],len);if(!arrow)return;const color=fixedColor||palette(this.options.palette,this.options.opacity,t);drawArrow(ctx,arrow,len,'rgba(1,8,18,.78)',3.4);drawArrow(ctx,arrow,len,color,1.45);});ctx.restore();if(!fixedColor&&this.options.palette==='magnitude')this.drawMagnitudeLegend(rect,vmax);},
    drawHeatmap(w,h,b){const ctx=this.ctx,rect=this.scene.getCanvasRect(),cols=90,rows=Math.max(20,Math.round(cols*rect.height/rect.width)),cw=rect.width/cols,ch=rect.height/rows,values=[];let max=0;ctx.save();for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const x=b.minX+(i+.5)/cols*(b.maxX-b.minX),y=b.minY+(j+.5)/rows*(b.maxY-b.minY),v=this.field.evaluate(x,y),m=Math.log1p(Math.hypot(...v));max=Math.max(max,m);values.push(m);}values.forEach((v,k)=>{ctx.fillStyle=heat(v/(max||1));ctx.fillRect(rect.left+(k%cols)*cw,rect.top+Math.floor(k/cols)*ch,cw+1,ch+1);});ctx.restore();},
    drawContours(w,h,b){const ctx=this.ctx,n=72,vals=[];let min=Infinity,max=-Infinity;for(let j=0;j<=n;j++)for(let i=0;i<=n;i++){const v=this.field.scalar(b.minX+i/n*(b.maxX-b.minX),b.minY+j/n*(b.maxY-b.minY));vals.push(v);if(Number.isFinite(v)){min=Math.min(min,v);max=Math.max(max,v);}}if(!Number.isFinite(min)||max===min)return;const rect=this.scene.getCanvasRect();ctx.save();ctx.translate(rect.left,rect.top);for(let l=1;l<8;l++){const level=min+l/8*(max-min),segments=contourSegments(vals,n,n,level,rect.width,rect.height);for(const [color,width] of [['rgba(2,8,18,.9)',3.2],['rgba(255,220,112,.82)',1.15]]){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();segments.forEach(([a,c])=>{ctx.moveTo(a[0],a[1]);ctx.lineTo(c[0],c[1]);});ctx.stroke();}}ctx.restore();},
    drawMagnitudeLegend(rect,vmax){const ctx=this.ctx,x=rect.left+14,y=rect.top+14,width=132,height=8,g=ctx.createLinearGradient(x,0,x+width,0);for(let i=0;i<=8;i++)g.addColorStop(i/8,magnitudeColor(i/8,1));ctx.save();ctx.fillStyle='rgba(2,8,18,.8)';ctx.fillRect(x-7,y-7,width+14,34);ctx.fillStyle=g;ctx.fillRect(x,y,width,height);ctx.fillStyle='#dcecff';ctx.font='10px system-ui';ctx.fillText('|F|  low',x,y+21);ctx.textAlign='right';ctx.fillText(`high  ${formatNumber(vmax)}`,x+width,y+21);ctx.restore();},
    drawCritical(b,map){const ctx=this.ctx;findCriticalPoints(this.field.evaluate,b,{grid:22}).forEach(p=>{const [x,y]=map(p.x,p.y);ctx.fillStyle=p.classification==='saddle'?'#ffb454':'#ff5d8f';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#dfefff';ctx.font='11px system-ui';ctx.fillText(p.classification,x+8,y-7);});}
  }
}
function niceStep(raw){const p=10**Math.floor(Math.log10(raw)),n=raw/p;return(n<2?1:n<5?2:5)*p;}
function drawArrow(ctx,arrow,len,color,width){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(arrow.x1,arrow.y1);ctx.lineTo(arrow.x2,arrow.y2);ctx.stroke();const head=Math.min(6.5,len*.32);ctx.beginPath();ctx.moveTo(arrow.x2,arrow.y2);ctx.lineTo(arrow.x2-head*Math.cos(arrow.angle-.55),arrow.y2-head*Math.sin(arrow.angle-.55));ctx.lineTo(arrow.x2-head*Math.cos(arrow.angle+.55),arrow.y2-head*Math.sin(arrow.angle+.55));ctx.closePath();ctx.fill();}
function palette(name,a,t=.5){return name==='magnitude'?magnitudeColor(t,a):name==='violet'?`rgba(178,115,255,${a})`:name==='gold'?`rgba(255,190,84,${a})`:name==='white'?`rgba(230,243,255,${a})`:`rgba(78,196,255,${a})`;}
function magnitudeColor(t,a){const stops=[[0,88,196,221],[.35,102,208,255],[.68,255,225,84],[1,252,98,85]],i=stops.findIndex(s=>t<=s[0]),hi=i<0?stops.length-1:Math.max(1,i),lo=hi-1,u=(t-stops[lo][0])/(stops[hi][0]-stops[lo][0]||1),mix=k=>Math.round(stops[lo][k]+(stops[hi][k]-stops[lo][k])*u);return `rgba(${mix(1)},${mix(2)},${mix(3)},${a})`;}
function heat(t){return `rgba(${Math.round(22+88*t)},${Math.round(20+36*t)},${Math.round(70+112*t)},${.07+.19*t})`;}
function formatNumber(value){return value>=1000?value.toExponential(1):value>=10?value.toFixed(1):value.toFixed(2);}
</script>
<style>.field-overlay{position:fixed;inset:0;z-index:2;pointer-events:none}</style>
